<?php

namespace ShortPixel\Controller;

if (! defined('ABSPATH')) {
	exit; // Exit if accessed directly.
}

use ShortPixel\Controller\Api\RequestManager;
use ShortPixel\Controller\View\ListMediaViewController as ListMediaViewController;
use ShortPixel\Controller\View\OtherMediaViewController as OtherMediaViewController;
use ShortPixel\Controller\View\OtherMediaFolderViewController as OtherMediaFolderViewController;

use ShortPixel\ShortPixelLogger\ShortPixelLogger as Log;
use ShortPixel\Notices\NoticeController as Notices;

//use ShortPixel\Controller\BulkController as BulkController;
use ShortPixel\Helper\UiHelper as UiHelper;
use ShortPixel\Helper\InstallHelper as InstallHelper;
use ShortPixel\Helper\UtilHelper;

use ShortPixel\Model\Image\ImageModel as ImageModel;
use ShortPixel\Model\AccessModel as AccessModel;

use ShortPixel\Controller\View\SettingsViewController as SettingsViewController;
use ShortPixel\Controller\Queue\QueueItems as QueueItems;
use ShortPixel\Controller\View\MultiSiteViewController;
use ShortPixel\Model\AiDataModel;
use ShortPixel\Model\Queue\QueueItem;
use ShortPixel\ViewController;

/**
 * Central AJAX dispatch table for the ShortPixel Image Optimiser plugin.
 *
 * ## Registered WP AJAX actions
 *
 * Every public `ajax_*` method and the two primary entry points are registered as WP
 * AJAX actions by the caller (typically `FrontController` or `ShortPixelPlugin`):
 *
 * - `wp_ajax_shortpixel_process_queue`   → ajax_processQueue()
 * - `wp_ajax_shortpixel_ajax`            → ajaxRequest()
 * - `wp_ajax_shortpixel_settings`        → settingsRequest()
 * - `wp_ajax_shortpixel_checkquota`      → ajax_checkquota()
 *
 * ## Request routing
 *
 * `ajaxRequest()` reads `$_POST['screen_action']` and routes to a dedicated protected
 * method.  Item-level actions (`optimizeItem`, `restoreItem`, `reOptimizeItem`, etc.)
 * work on a single `$_POST['id']` + `$_POST['type']` pair.  Bulk and settings actions
 * (`createBulk`, `startBulk`, `finishBulk`, `applyBulkSelection`, `startRestoreAll`,
 * `toolsRemoveAll`, `toolsRemoveBackup`, `loadLogFile`, …) are also dispatched here.
 *
 * `settingsRequest()` reads `$_POST['screen_action']` and routes every recognised
 * settings form action to `settingsFormSubmit()`, which delegates to
 * `SettingsViewController`.
 *
 * ## Authentication / authorisation
 *
 * 1. Every public entry point calls `checkNonce()` first; a bad or missing nonce sends
 *    a JSON error with `error = NONCE_FAILED` and exits.
 * 2. `checkActionAccess()` maps each action to a minimum capability level via
 *    `AccessModel::userIsAllowed()`.  On failure it sends `error = NO_ACCESS` and exits.
 * 3. Image-scoped actions additionally call `checkImageAccess()` which verifies
 *    `AccessModel::imageIsEditable()`.
 * 4. Queue-processing calls `checkProcessorKey()` to ensure only one JS processor
 *    drives the queue at a time; competing tabs receive `error = PROCESSOR_ACTIVE`.
 *
 * ## Response shape
 *
 * All responses go through `send()`, which calls `wp_send_json()` and exits.  The
 * JSON payload always contains `status` (bool/int) and, when set, `error` (one of the
 * class constants below).  The current `processorKey` is appended to every response so
 * that the JS side can update its session token.
 *
 * @package ShortPixel\Controller
 */
class AjaxController
{
	/** Sent when a second JS processor tries to claim the queue while one is already active. */
	const PROCESSOR_ACTIVE = -1;
	/** Sent when `wp_verify_nonce()` returns false. */
	const NONCE_FAILED = -2;
	/** Sent when `screen_action` does not match any known case in the dispatch switch. */
	const NO_ACTION = -3;
	/** Sent when the API key check fails (reserved, not yet used in dispatch). */
	const APIKEY_FAILED = -4;
	/** Sent when no image credits remain (reserved). */
	const NOQUOTA = -5;
	/** Sent on unrecoverable server errors (reserved). */
	const SERVER_ERROR = -6;
	/** Sent when capability or image-ownership check fails. */
	const NO_ACCESS = -7;

	private static $instance;

	/**
	 * Return the singleton instance, creating it on first call.
	 *
	 * @return static The singleton AjaxController instance.
	 */
	public static function getInstance()
	{
		if (is_null(self::$instance))
			self::$instance = new static();

		return self::$instance;
	}

	/**
	 * Return the current bulk-processor secret key from cache.
	 *
	 * The key is generated by the JS processor and stored in a short-lived cache entry
	 * (`bulk-secret`). Returns false when no key is set or the stored value is empty.
	 *
	 * Also used by the localise script to provide the initial key to JavaScript.
	 *
	 * @return string|false The processor key, or false if not set.
	 */
	public function getProcessorKey()
	{
		// Get a Secret Key.
		$cacheControl = new CacheController();
		$bulkSecret = $cacheControl->getItem('bulk-secret');

		$secretKey = $bulkSecret->getValue();
		if (is_null($secretKey) || strlen($secretKey) == 0 || $secretKey === 'null') {
			$secretKey = false;
		}
		return $secretKey;
	}

	/**
	 * Verify that the current request is the authorised JS processor.
	 *
	 * Reads `$_POST['bulk-secret']` and `$_POST['isBulk']` to determine whether this
	 * request should be treated as the active processor.  A request qualifies when:
	 * - no key is currently stored (first-come-first-served), or
	 * - the posted secret matches the stored key, or
	 * - `isBulk` is a truthy boolean string.
	 *
	 * When the caller qualifies and posts a different secret, the stored key is updated
	 * and its TTL reset to two minutes.
	 *
	 * On failure, sends a JSON error (`error = PROCESSOR_ACTIVE`) and exits; does not
	 * return false.
	 *
	 * @return void
	 */
	protected function checkProcessorKey()
	{
		$processKey = $this->getProcessorKey();
		// phpcs:ignore -- Nonce is checked
		$bulkSecret = isset($_POST['bulk-secret']) ? sanitize_text_field(wp_unslash($_POST['bulk-secret'])) : false;
		// phpcs:ignore -- Nonce is checked
		$isBulk = isset($_POST['isBulk']) ? filter_var(sanitize_text_field(wp_unslash($_POST['isBulk'])), FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE) : false;

		$is_processor = false;
		if ($processKey == false && $bulkSecret !== false) {
			$is_processor = true;
		} elseif ($processKey == $bulkSecret) {
			$is_processor = true;
		} elseif ($isBulk) {
			$is_processor = true;
		}

		// Save new ProcessorKey
		if ($is_processor && $bulkSecret !== $processKey) {
			$cacheControl = new CacheController();
			$cachedObj = $cacheControl->getItem('bulk-secret');

			$cachedObj->setValue($bulkSecret);
			$cachedObj->setExpires(2 * MINUTE_IN_SECONDS);
			$cachedObj->save();
		}

		if (false === $is_processor) {
			$json = new \stdClass;
			$json->message = __('Processor is active in another window', 'shortpixel-image-optimiser');
			$json->status = false;
			$json->error = self::PROCESSOR_ACTIVE; // processor active
			$this->send($json);
		}
	}

	/**
	 * Render the inline status cell HTML for a single media or custom item.
	 *
	 * Reads `$_POST['type']` ('media' or 'custom', defaults to 'media') and
	 * `$_POST['id']` (int, the image ID).  Verifies image access, then delegates to
	 * `ListMediaViewController::doColumn()` (media) or
	 * `OtherMediaViewController::doActionColumn()` (custom) via output buffering.
	 *
	 * Returns a stdClass (not sent directly — caller passes it on to `send()`):
	 * - `$json->$type->itemView`        string  Rendered HTML for the status column.
	 * - `$json->$type->is_optimizable`  bool    Whether the item can be queued.
	 * - `$json->$type->is_restorable`   bool    Whether the item can be restored.
	 * - `$json->$type->id`              int     The requested item ID.
	 * - `$json->$type->image`           array   Keys: width, height, extension.
	 * - `$json->$type->results`         null    Always null from this method.
	 * - `$json->$type->is_error`        bool    Always false from this method.
	 * - `$json->status`                 bool    Always true.
	 *
	 * @return \stdClass JSON response object.
	 */
	protected function getItemView()
	{
		// phpcs:ignore -- Nonce is checked
		$type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'media';
		// phpcs:ignore -- Nonce is checked
		$id = isset($_POST['id']) ? intval($_POST['id']) : false;
		$result = '';


		$item = \wpSPIO()->filesystem()->getImage($id, $type);

		$this->checkImageAccess($item);

		if ($id > 0) {
			if ($type == 'media') {
				ob_start();
				$control = ListMediaViewController::getInstance();
				$control->doColumn('wp-shortPixel', $id);
				$result = ob_get_contents();
				ob_end_clean();
			}
			if ($type == 'custom') {
				ob_start();
				$control = new OtherMediaViewController();
				$control->doActionColumn($item);
				$result = ob_get_contents();
				ob_end_clean();
			}
		}

		$json = new \stdClass;
		$json->$type = new \stdClass;
		$json->$type->itemView = $result;
		$json->$type->is_optimizable = (false !== $item) ? $item->isProcessable() : false;
		$json->$type->is_restorable = (false !== $item)  ? $item->isRestorable() : false;
		$json->$type->id = $id;
		$json->$type->image = [
			'width' => $item->get('width'), 
			'height' => $item->get('height'), 
			'extension' => $item->getExtension(), 
		];
		$json->$type->results = null;
		$json->$type->is_error = false;
		$json->status = true;

		return $json;
		// $this->send($json);
	}

	/**
	 * AJAX handler: process the next batch of items from the optimisation queue.
	 *
	 * Action: `wp_ajax_shortpixel_process_queue`.
	 *
	 * Expected `$_POST` fields:
	 * - `nonce`      string  WP nonce for action 'processing'.
	 * - `isBulk`     string  'true' or 'false'; sets bulk mode on the queue controller.
	 * - `queues`     string  Comma-separated list of queue names (default 'media,custom').
	 * - `bulk-secret` string Optional processor key for multi-tab coordination.
	 *
	 * Exits with `wp_send_json()` on success or any guard failure.
	 *
	 * @return void
	 */
	public function ajax_processQueue()
	{
		$this->checkNonce('processing');
		$this->checkActionAccess('processQueue', 'is_author');
		$this->checkProcessorKey();

		ErrorController::start(); // Capture fatal errors for us.

		// Notice that POST variables are always string, so 'true', not true.
		// phpcs:ignore -- Nonce is checked
		$isBulk = (isset($_POST['isBulk']) && $_POST['isBulk'] == 'true') ? true : false;
		// phpcs:ignore -- Nonce is checked
		$queue = (isset($_POST['queues'])) ? sanitize_text_field($_POST['queues']) : 'media,custom';

		$queues = array_filter(explode(',', $queue), 'trim');

		$control = new QueueController(['is_bulk' => $isBulk]);
		$result = $control->processQueue($queues);

		$this->send($result);
	}

	/**
	 * Attempt to claim the processor role after losing a multi-tab race.
	 *
	 * Called from `ajaxRequest()` under the `recheckActive` action.  If the previous
	 * processor has released the key (or its TTL expired), this call will succeed and
	 * the JS side can resume processing.  On failure `checkProcessorKey()` exits with
	 * `error = PROCESSOR_ACTIVE`.
	 *
	 * On success sends:
	 * - `status`  bool   true
	 * - `message` string Confirmation text.
	 *
	 * @return void
	 */
	protected function recheckActive()
	{
		// If not processor, this ends the processing and sends JSON.
		$this->checkProcessorKey();

		$json = new \stdClass;
		$json->message = __('Became processor', 'shortpixel-image-optimiser');
		$json->status = true;
		$this->send($json);
	}

	/**
	 * Primary AJAX dispatcher for screen-level actions.
	 *
	 * Action: `wp_ajax_shortpixel_ajax`.
	 *
	 * Verifies the nonce (`ajax_request`) and minimum capability (`is_author`), then
	 * dispatches to the appropriate protected method based on `$_POST['screen_action']`.
	 * Several actions re-check capability at a higher level inside their handler.
	 *
	 * Common `$_POST` fields:
	 * - `nonce`         string   WP nonce for action 'ajax_request'.
	 * - `screen_action` string   Identifies the operation to perform (see switch below).
	 * - `id`            int      Image/folder ID (most item actions).
	 * - `type`          string   'media' or 'custom' (defaults to both for status queries).
	 *
	 * All responses are sent via `send()` and the method exits.
	 *
	 * @return void
	 */
	public function ajaxRequest()
	{
		$this->checkNonce('ajax_request');
		ErrorController::start(); // Capture fatal errors for us.

		$this->checkActionAccess('ajax', 'is_author');

		// phpcs:ignore -- Nonce is checked
		$action = isset($_POST['screen_action']) ? sanitize_text_field($_POST['screen_action']) : false;
		// phpcs:ignore -- Nonce is checked
		$typeArray = isset($_POST['type'])  ? array(sanitize_text_field($_POST['type'])) : array('media', 'custom');
		// phpcs:ignore -- Nonce is checked
		$id = isset($_POST['id']) ? intval($_POST['id']) : false;

		$json = new \stdClass;
		foreach ($typeArray as $type) {
			$json->$type = new \stdClass;
			//      $json->$type->id = $id;  // This one is off because item_id belongs to results -> itemResult.
			$json->$type->results = null;
			//      $json->$type->is_error = false;
			$json->status = false;
		}

		$data = array('id' => $id, 'typeArray' => $typeArray, 'action' => $action);

		if (count($typeArray) == 1) // Actions which need specific type like optimize / restore.
		{
			$data['type'] = $typeArray[0];
			unset($data['typeArray']);
		}

		// First Item action,  alphabet.  Second general actions, alpha.
		switch ($action) {
			case 'cancelOptimize':
				$json = $this->cancelOptimize($json, $data);
				break;
			case 'getItemEditWarning': // Has to do with image editor
				$json = $this->getItemEditWarning($json, $data);
				break;
			case 'getComparerData':
				$json = $this->getComparerData($json, $data);
				break;
			case 'getItemView':
				$json = $this->getItemView($json, $data);
				break;
			case 'markCompleted':
				$json = $this->markCompleted($json, $data);
				break;
			case 'optimizeItem':
				$json = $this->optimizeItem($json, $data);
				break;
			case "redoLegacy":
				$this->redoLegacy($json, $data);
				break;
			case 'restoreItem':
				$json = $this->restoreItem($json, $data);
				break;
			case 'reOptimizeItem':
				$json = $this->reOptimizeItem($json, $data);
				break;
			case 'settings/purgecdncache': 
				$json = $this->purgeCDNCache($json, $data); 
			break;
			case 'settings/importexport':
				$json = $this->importexportSettings($json, $data);
			break; 
			case 'ai/requestalt': 
				$json = $this->requestAlt($json, $data);	
			break; 
			case 'ai/getAltData': 
				$json = $this->getAltData($json, $data);
			break; 
			case 'ai/undoAlt':
				$json = $this->undoAltData($json, $data);			
			break;
			case 'ai/redoAiReplacement': 
				$json = $this->redoAiReplacement($json, $data); 
			break;
			case 'unMarkCompleted':
				$json = $this->unMarkCompleted($json, $data);
				break;
			case 'applyBulkSelection':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->applyBulkSelection($json, $data);
				break;
			case 'createBulk':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->createBulk($json, $data);
				break;
			case 'finishBulk':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->finishBulk($json, $data);
				break;
			case 'startBulk':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->startBulk($json, $data);
				break;
			case 'startRestoreAll':
				$this->checkActionAccess($action, 'is_admin_user');
				$json = $this->startRestoreAll($json, $data);
				break;
			case 'startBulkUndoAI':
				$this->checkActionAccess($action, 'is_admin_user');
				$json = $this->startUndoAI($json, $data);
				break;
			case 'startMigrateAll':
				$this->checkActionAccess($action, 'is_admin_user');
				$json = $this->startMigrateAll($json, $data);
				break;
			case 'startBulkRedoAiReplacement':
				$this->checkActionAccess($action, 'is_admin_user');
				$json = $this->startBulkRedoAiReplacement($json, $data);
				break;			
			case 'startRemoveLegacy':
				$this->checkActionAccess($action, 'is_admin_user');
				$json = $this->startRemoveLegacy($json, $data);
				break;
			case "toolsRemoveAll":
				$this->checkActionAccess($action, 'is_super_admin');
				$json = $this->removeAllData($json, $data);
				break;
			case "toolsRemoveBackup":
				$this->checkActionAccess($action, 'is_super_admin');
				$json = $this->removeBackup($json, $data);
				break;
			case "loadLogFile":
				$this->checkActionAccess($action, 'is_editor');
				$data['logFile'] = isset($_POST['loadFile']) ? sanitize_text_field($_POST['loadFile']) : null;
				$json = $this->loadLogFile($json, $data);
				break;

			case 'refreshFolder':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->refreshFolder($json, $data);
				break;
			// CUSTOM FOLDERS
			case 'removeCustomFolder':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->removeCustomFolder($json, $data);
				break;
			case 'browseFolders':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->browseFolders($json, $data);
				break;
			case 'addCustomFolder':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->addCustomFolder($json, $data);
				break;
			case 'scanNextFolder':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->scanNextFolder($json, $data);
				break;
			case 'resetScanFolderChecked':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->resetScanFolderChecked($json, $data);
				break;
			case 'recheckActive':
				$this->checkActionAccess($action, 'is_editor');
				$json = $this->recheckActive($json, $data);
				break;
			case 'settings/changemode':
				$this->handleChangeMode($data);
				break;
			case 'settings/getAiExample': 
				$this->checkActionAccess($action, 'is_admin_user');
				$this->getSettingsAiExample($data);
			break; 
			case 'settings/setAiImageId': 
				$this->checkActionAccess($action, 'is_admin_user');
				$this->setSettingsAiImage($data);
			break; 
			case 'settings/getNewAiImagePreview': 
				$this->getNewAiImagePreview($data);
			break;
			case 'media/getEditorPopup': 
				$this->getEditorPopup($data);
			break; 
			case 'media/getEditorPreview': 
				$this->getEditorPreview($data);
			break;
			case 'media/replaceFileName': 
				$this->replaceFileName($data);
			break; 
			default:
				$json->$type->message = __('Ajaxrequest - no action found', 'shortpixel-image-optimiser');
				$json->error = self::NO_ACTION;
			break;
		}
		$this->send($json);
	}

	/**
	 * AJAX dispatcher for settings-page form submissions.
	 *
	 * Action: `wp_ajax_shortpixel_settings`.
	 *
	 * Verifies the nonce (`settings_request`) and requires `is_admin_user` capability.
	 * Recognised `$_POST['screen_action']` values are routed to `settingsFormSubmit()`:
	 * `save-settings` (site settings form), `save-multi-settings` (network settings
	 * form), `action_addkey`, `action_debug_*`, `action_request_new_key`,
	 * `action_end_quick_tour`.  Any other value logs an error and exits with '0'.
	 *
	 * @return void
	 */
	public function settingsRequest()
	{
		$this->checkNonce('settings_request');
		ErrorController::start(); // Capture fatal errors for us.

		$action = isset($_POST['screen_action']) ? sanitize_text_field($_POST['screen_action']) : false;

		$this->checkActionAccess($action, 'is_admin_user');

		switch ($action) {
			case 'save-settings': // usual settings 
			case 'save-multi-settings': // multisite settings
			case 'action_addkey':
			case 'action_debug_redirectBulk':
			case 'action_debug_removePrevented':
			case 'action_debug_removeProcessorKey':
			case 'action_debug_resetNotices':
			case 'action_debug_resetQueue':
			case 'action_debug_resetquota':
			case 'action_debug_resetStats':
			case 'action_debug_triggerNotice':
			case 'action_request_new_key':
			case 'action_debug_editSetting':
			case 'action_end_quick_tour':
				$this->settingsFormSubmit($action);
				break;
			break;
			default:
				Log::addError('Issue with settingsRequest, not valid action');
				$json = new \stdClass;
				$json->result = false;
				$json->message = __('Settings requests with invalid action', 'shortpixel-image-optimiser');
				$this->send($json);
				break;
		}
	}

	/**
	 * Delegate a settings form action to the settings view controller.
	 *
	 * Instantiates `MultiSiteViewController` for `save-multi-settings` (network
	 * settings form) or `SettingsViewController` otherwise, marks it as processing
	 * an AJAX save, sets the redirect URL from `$_POST['request_url']`, and calls
	 * the action method on the view controller if it exists, otherwise falls back
	 * to `load()`.  Exits afterwards.
	 *
	 * @param string $action The action method name to invoke on the view controller.
	 * @return void  Always exits.
	 */
	protected function settingsFormSubmit($action)
	{
		if ('save-multi-settings' === $action)
		{
			$viewController =  new MultiSiteViewController();
		}
		else 
		{
			$viewController =  new SettingsViewController();
		}
		

		$viewController->indicateAjaxSave(); // set ajax save method

		$url = isset($_POST['request_url']) ? sanitize_text_field($_POST['request_url']) : null;
		if (is_null($url)) {
			Log::addError('Ajax : redirect URL not set!');
		}
		$viewController->setControllerURL($url); // set url for redirects, otherwise set by route / plugin
		if (method_exists($viewController, $action)) {
			$viewController->$action();
		} else {
			$viewController->load();
		}

		exit('ajaxcontroller - formsubmit');
	}

	/**
	 * Build and send the HTML popup for the AI media editor (remove-background / upscale).
	 *
	 * Reads `$_POST['id']` (int, media attachment ID) and optional
	 * `$_POST['action_name']` (string, default 'replace').  Verifies image access, finds
	 * the best preview image, and renders the `snippets/media-popup` view.
	 *
	 * Sends:
	 * - `item_id`     int     Attachment ID.
	 * - `popup`       string  Rendered HTML for the modal.
	 * - `action_name` string  The resolved action name.
	 *
	 * @param array $data Dispatch data array (unused; values are read directly from $_POST).
	 * @return void  Calls send() and exits.
	 */
	protected function getEditorPopup($data)
	{
		 $item_id = intval($_POST['id']);
		 $mediaItem = $this->getMediaItem($item_id, 'media');
		 $this->checkImageAccess($mediaItem);

		 $action_name = isset($_POST['action_name']) ? sanitize_text_field($_POST['action_name']) : 'replace'; 

		 $previewImage = UiHelper::findBestPreview($mediaItem, 800);

		 $json = new \stdClass; 
		 $json->item_id = $item_id; 

		 $post = get_post($item_id); 

		 $originalImage = $mediaItem; 
		 if ($mediaItem->isScaled())
		 {
			 $originalImage = $mediaItem->getOriginalFile(); 
		 }
				 
		 $view = new ViewController();
		 $view->addData([
			'previewImage' => $previewImage, 
			'originalImage' => $originalImage, 
			'placeholderImage' => \wpSPIO()->plugin_url('res/img/bulk/placeholder.svg'), 
			'item_id' => $item_id, 
			'post_title' => $post->post_title, 
			'action_name' => $action_name, 
			]
		 ); 

		 $json->popup = $view->returnView('snippets/media-popup'); 
		 $json->action_name = $action_name; 
		 

		 $this->send($json);

	}
	/**
	 * Execute a remove-background or upscale action and poll until the API result is ready.
	 *
	 * Reads several `$_POST` fields depending on `action_name`:
	 * - `id`               int     Media attachment ID.
	 * - `is_preview`       bool    When true, the result is not saved to the media library.
	 * - `action_name`      string  'remove' (background removal) or 'scale' (upscale).
	 * - `opener`           string  'edit', 'gallery', or 'gutenberg' — controls the redirect URL.
	 * - `attached_post_id` int     ID of the post the image is attached to.
	 * - `newFileName`      string  Sanitised desired filename for the new attachment.
	 * - `newPostTitle`     string  Post title for the new attachment.
	 * - `refresh`          bool    Force cache refresh on the resulting image.
	 *
	 * For `action_name === 'remove'`:
	 * - `background_type`         string 'transparent' or 'solid'.
	 * - `background_color`        string Hex colour when type is 'solid'.
	 * - `background_transparency` string Hex transparency component.
	 *
	 * For `action_name === 'scale'`:
	 * - `scale` int  Scale factor (default 2).
	 *
	 * Polls the API in a loop (up to 15 iterations with 3-second sleeps) until
	 * `is_done` is true, then sends the result and exits.  Sends a timeout error when
	 * the limit is exceeded.
	 *
	 * @param array $data Dispatch data array; `$data['id']` is used as the attachment ID.
	 * @return void  Calls send() and exits.
	 */
	protected function getEditorPreview($data)
	{
		$item_id = $data['id'];
		$is_preview = true; // default to no action 
		$is_preview = (isset($_POST['is_preview'])) ? filter_var(sanitize_text_field($_POST['is_preview']), FILTER_VALIDATE_BOOL) : $is_preview; 

		$action_name = isset($_POST['action_name']) ? sanitize_text_field($_POST['action_name']) : 'remove'; 

		$mediaItem = $this->getMediaItem($item_id, 'media');

		$this->checkImageAccess($mediaItem);
		$qItem = QueueItems::getImageItem($mediaItem);

		// General needed: 
		$opener = isset($_POST['opener']) ? sanitize_text_field($_POST['opener']) : ''; 
		$attached_post_id = isset($_POST['attached_post_id']) ? intval($_POST['attached_post_id']) : 0; 
		$newFileName = isset($_POST['newFileName']) ? sanitize_file_name($_POST['newFileName']) : false; 
		$newPostTitle = isset($_POST['newPostTitle']) ? sanitize_text_field($_POST['newPostTitle']) : ''; 
		$refresh = isset($_POST['refresh']) ? filter_var(sanitize_text_field($_POST['refresh']), FILTER_VALIDATE_BOOL) : false;  

		$args = [
			'newFileName' => $newFileName, 
			'newPostTitle' => $newPostTitle, 
			'refresh' => $refresh, 
			'attached_post_id' => $attached_post_id, 
		]; 

		// For remove background : 
		if ('remove' === $action_name)
		{
			$backgroundType = isset($_POST['background_type']) ? sanitize_text_field($_POST['background_type']) : 'transparent'; 
			$backgroundColor = isset($_POST['background_color']) ? sanitize_text_field($_POST['background_color']) : false; 
			$backgroundTransparency = isset($_POST['background_transparency']) ? sanitize_text_field($_POST['background_transparency']) : '00';
			if ('solid' == $backgroundType)
			{
				 $args['replace_color'] = $backgroundColor; 
				 $args['replace_transparency'] = $backgroundTransparency; 
				 $args['do_transparent'] = false;
			}
			else
			{
				 $args['do_transparent'] = true; 
			}

			$optimizer = $qItem->getApiController('remove_background');
			$qItem->newRemoveBackgroundAction(array_merge(['is_preview' => $is_preview], $args));

		}
		elseif ('scale' == $action_name) 		// For image scaling: 		
		{
			$args['scale'] = isset($_POST['scale']) ? intval($_POST['scale']) : 2; 

			$optimizer = $qItem->getApiController('scale_image');
			$qItem->newScaleImageAction(array_merge(['is_preview' => $is_preview], $args));
		}


		//$args = []; 
		
		/*$args['do_transparent'] = ('transparent' == $backgroundType) ? true : false; 
		$args['newFileName'] = $newFileName; 
		$args['newPostTitle'] = $newPostTitle; 
		$args['refresh'] = $refresh;
		$args['attached_post_id'] = $attached_post_id; 
	*/		

		$optimizer->sendToProcessing($qItem);
		$optimizer->handleAPIResult($qItem);  

		$result = $qItem->result(); 
		$qItem->data()->tries++; 
		
	//	$state = 'requestAlt'; // mimic here the double task of the Ai gen. 
		$is_done = false; 
		$i = 0; 

		while (false === $is_done)
		{
			if (false === property_exists($result, 'is_done') || $result->is_done === false)
			{ 
				// Any subsequent request *must* be hard refresh no or it hangs.

				$optimizer->sendToProcessing($qItem);
				$optimizer->handleAPIResult($qItem);  
				$qItem->data()->tries++; 

				$result = $qItem->result();
			}
			
			if (property_exists($result, 'is_done') && true === $result->is_done)
			{

				if ($result->apiStatus === RequestManager::STATUS_SUCCESS && false === $is_preview )
				{
					$new_attach_id = $qItem->result()->new_attach_id; 
					if ('edit' == $opener)
					{
						$redirect = admin_url('post.php?post=' . $new_attach_id . '&action=edit'); 			 
					}
					elseif ('gallery' == $opener)
					{
						$redirect = admin_url('upload.php?item=' . $new_attach_id);	 
					}
					elseif ('gutenberg' == $opener)
					{
						$redirect = 'gutenberg'; // overload for JS processing
						$attachment = get_post($new_attach_id); 
						$js_attach = wp_prepare_attachment_for_js($attachment); 
						$qItem->addResult(['file' => $js_attach]);
					}

					if (isset($redirect))
					{
						$qItem->addResult([ 'redirect' => $redirect   ]); 
					}
					$result = $qItem->result();
				}
					$this->send($result->forReturn());
								
				exit();
			}

			if ($i >= 15) // safeguard. 
			{
				$result = [
					'is_error' => true, 
					'is_done' => true, 
					'message' => __('Limit of attempts exceeded. Possible connection issue. Try again later. ', 'shortpixel-image-optimiser'),
				]; 
				
				$this->send($result);
				exit('Timeout');
				break; 
			}

			sleep(3); // prevent in case of fast connection hammering the API
			$i++; 
		}
	}

	/**
	 * Load an image model by ID and type from the filesystem controller.
	 *
	 * Thin wrapper around `FileSystemController::getImage()`.
	 *
	 * @param int    $id   The image ID (attachment post ID for 'media', custom ID for 'custom').
	 * @param string $type The image type: 'media' or 'custom'.
	 * @return \ShortPixel\Model\Image\MediaLibraryModel|\ShortPixel\Model\Image\CustomImageModel|false
	 *         The image model, or false if not found.
	 */
	protected function getMediaItem($id, $type)
	{
		$fs = \wpSPIO()->filesystem();
		return $fs->getImage($id, $type);
	}

	

	/**
	 * Return optimisation/restoration status flags for use in the WP image editor warning.
	 *
	 * Reads `$_POST['id']` (int, media attachment ID) and verifies image access.  When
	 * the item can be loaded, overwrites `$json` with a fresh object containing:
	 * - `id`            int     Attachment ID.
	 * - `is_restorable` string  'true' or 'false'.
	 * - `is_optimized`  string  'true' or 'false'.
	 *
	 * @param \stdClass $json Incoming JSON accumulator (replaced on success).
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function getItemEditWarning($json, $data)
	{
		$id = intval($_POST['id']);
		$mediaItem = $this->getMediaItem($id, 'media');
		$this->checkImageAccess($mediaItem);

		if (is_object($mediaItem)) {
			$json = new \stdClass;
			$json->id = $id;
			$json->is_restorable = ($mediaItem->isRestorable()) ? 'true' : 'false';
			$json->is_optimized = ($mediaItem->isOptimized()) ? 'true' : 'false';
		} else {
		}
		return $json;
	}

	/**
	 * Add a single image to the single-item optimisation queue.
	 *
	 * Reads from `$_POST`:
	 * - `id`              int     Image ID.
	 * - `type`            string  'media' or 'custom' (default 'media').
	 * - `compressionType` string  Optional compression level override.
	 * - `flags`           string  Optional 'force' to bypass exclusion rules.
	 *
	 * Any existing `isOptimizePrevented` flag on the item is cleared before queuing.
	 *
	 * Returns (does not call `send()`):
	 * - `$json->$type->results`  array   Single-element array with the queue result.
	 * - `$json->$type->qstatus`  mixed   Last queue status from `QueueController`.
	 *
	 * @return \stdClass JSON response object.
	 */
	protected function optimizeItem()
	{
		$id = intval($_POST['id']);
		$type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'media';
		$compressionType = isset($_POST['compressionType']) ? sanitize_text_field($_POST['compressionType']) : false; 
		$flags = isset($_POST['flags']) ? sanitize_text_field($_POST['flags']) : false;

		$mediaItem = $this->getMediaItem($id, $type);

		$this->checkImageAccess($mediaItem);

		// if order is given, remove barrier and file away.
		if ($mediaItem->isOptimizePrevented() !== false)
		{
			$mediaItem->resetPrevent();
		}

		$control = new QueueController();
		$json = new \stdClass;
		$json->$type = new \stdClass;

		$args = [];

		if ('force' === $flags) {
			$args['forceExclusion'] =  true;
		}

		if (false !== $compressionType)
		{
			 $args['compressionType'] = $compressionType; 
		}

		$json->$type->results = [$control->addItemToQueue($mediaItem, $args)];
		$json->$type->qstatus = $control->getLastQueueStatus();
		return $json;
	}

	/**
	 * Purge the configured CDN cache via CDNController.
	 *
	 * Requires `is_admin_user` capability (re-checked inside this method).
	 * Reads `$_POST['purge']` (string, default 'cssjs') to determine what to purge.
	 *
	 * Returns:
	 * - `$json->settings->results` mixed  Result from `CDNController::purgeCDN()`.
	 * - `$json->status`            bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function purgeCDNCache($json, $data)
	{
		$this->checkActionAccess('purge', 'is_admin_user');

		$purge =  isset($_POST['purge']) ? sanitize_text_field($_POST['purge']) : 'cssjs'; 

		$CDNController = new \ShortPixel\Controller\Front\CDNController();
		$result = $CDNController->purgeCDN(['purge' => $purge]);

		$json->settings->results = $result;
		$json->status = true;

		return $json;
	}

				
	/**
	 * Handle settings import or export requests.
	 *
	 * Requires `is_admin_user` capability.  Reads `$_POST['actionType']` ('import' or
	 * 'export', default 'export').
	 *
	 * For `export`: serialises all settings via `SettingsModel::getExport()` to JSON and
	 * returns the string in `$json->settings->exportData`.
	 *
	 * For `import`: reads `$_POST['importData']` (JSON string), validates it, and
	 * iterates over each key/value pair calling `$settings->$name = $value` for known
	 * settings.  Unknown keys produce warning messages.
	 *
	 * Returns:
	 * - `$json->settings->results`    array   Import result with `is_error` bool and
	 *                                          `messages` array (import) or `message` string (export/error).
	 * - `$json->settings->exportData` string  JSON-encoded settings data (export only).
	 * - `$json->status`               bool    true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function importexportSettings($json, $data)
	{
		$action = (isset($_POST['actionType'])) ? sanitize_text_field($_POST['actionType']) : 'export';
		$this->checkActionAccess($action, 'is_admin_user');
		$settings = \wpSPIO()->settings();

		if ('import' === $action)
		{
			$importdata = (isset($_POST['importData'])) ? sanitize_text_field(trim($_POST['importData'])) : false; 
			$importdata = stripslashes($importdata); 
			$importdata = trim($importdata); 

			if (false === $importdata || 0 == strlen($importdata))
			{
				 $json->settings->results = ['is_error' => true, 'message' => __('Import contained empty field', 'shortpixel-image-optimiser')];
			}
			elseif (true ===  UtilHelper::validateJson($importdata) )
			{
				//$result = ['is_error' => false];
				$messages = []; 

				$importjson = json_decode($importdata, true);
				Log::addInfo('JSON Import: ', $importjson);
				$counter = 0;
				foreach($importjson as $name => $value )
				{
					if (false === $settings->exists($name))
					{
						$messages[] = sprintf(__('Field with name %s does not exist in current version', 'shortpixel-image-optimiser'), $name);
					}
					else
					{
						 $settings->$name = $value;
						 $counter++;
					}
				}

				$messages[] = sprintf(__('%s settings imported! Reload page to see changes', 'shortpixel-image-optimiser'), $counter); 
				$json->settings->results = ['is_error' => false, 'messages' => $messages];
		 
			}
			else
			{
				$json->settings->results = ['is_error' => true, 
				'message' => sprintf(__('Invalid JSON sent: %s', 'shortpixel-image-optimiser'), json_last_error_msg())];
			}

		}
		else
		{	
			$data = $settings->getExport(); 
			
			$json->settings->exportData = json_encode($data);
			$json->settings->message = __('Export completed. Copy the string below', 'shortpixel-image-optimiser');
			
		}
		
		$json->status = true; 
		return $json;
	}

	/**
	 * Manually mark an image as completed (excluded from further optimisation).
	 *
	 * Reads `$_POST['id']` and `$_POST['type']`.  Calls
	 * `ImageModel::markCompleted()` with status `FILE_STATUS_MARKED_DONE`, then
	 * builds a queue-item result for the JS layer.
	 *
	 * Returns:
	 * - `$json->$type->results` array  Single-element array with the queue result.
	 * - `$json->status`         bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function markCompleted($json, $data)
	{
		$id = intval($_POST['id']);
		$type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'media';

		$imageModel = $this->getMediaItem($id, $type);

		$this->checkImageAccess($imageModel);

		$imageModel->markCompleted(__('This item has been manually marked as completed', 'shortpixel-image-optimiser'), ImageModel::FILE_STATUS_MARKED_DONE);

		$qItem = QueueItems::getImageItem($imageModel);
		$qItem->addResult([
			'fileStatus' => ImageModel::FILE_STATUS_SUCCESS, 
			'item_id' => $id, 
			'message' => __('Item marked as completed', 'shortpixel-image-optimiser'), 
			'is_done' => true, 
			'is_error' => false, 
		]);

/*		$json->$type->fileStatus = ImageModel::FILE_STATUS_SUCCESS; // great success!

		$json->$type->result = new \stdClass;

		$json->$type->result->item_id = $id;
		$json->$type->result->message = __('Item marked as completed', 'shortpixel-image-optimiser');
		$json->$type->result->is_done = true;
		$json->$type->result->is_error = false;
*/
		$json->$type->results = [$qItem->result()];
		$json->status = true;

		return $json;
	}

	/**
	 * Remove the manual-completed mark from an image, re-enabling it for optimisation.
	 *
	 * Reads `$_POST['id']` and `$_POST['type']`.  Calls `ImageModel::resetPrevent()`.
	 *
	 * Returns:
	 * - `$json->$type->results` array  Single-element array with the queue result.
	 * - `$json->status`         bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function unMarkCompleted($json, $data)
	{
		$id = intval($_POST['id']);
		$type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'media';

		$imageModel = $this->getMediaItem($id, $type);

		$this->checkImageAccess($imageModel);

		$imageModel->resetPrevent();

		$qItem = QueueItems::getImageItem($imageModel);
		$qItem->addResult([
			'fileStatus' => ImageModel::FILE_STATUS_SUCCESS, 
			'item_id' => $id, 
			'message' => __('Item unmarked', 'shortpixel-image-optimiser'), 
			'is_done' => true, 
			'is_error' => false, 
		]);

		$json->$type->results = [$qItem->result()];
		$json->status = true;

		return $json;
	}

	/**
	 * Remove an image from the optimisation queue without optimising it.
	 *
	 * Reads `$_POST['id']` and `$_POST['type']`.  Calls `ImageModel::dropFromQueue()`.
	 *
	 * Returns:
	 * - `$json->$type->results` array  Single-element array with the queue result.
	 * - `$json->status`         bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function cancelOptimize($json, $data)
	{
		$id = intval($_POST['id']);
		$type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'media';

		$mediaItem = $this->getMediaItem($id, $type);

		$this->checkImageAccess($mediaItem);

		$mediaItem->dropFromQueue();


		$qItem = QueueItems::getImageItem($mediaItem);
		$qItem->addResult([
			'fileStatus' => ImageModel::FILE_STATUS_SUCCESS, 
			'item_id' => $id, 
			'message' => __('Item removed from queue', 'shortpixel-image-optimiser'), 
			'is_done' => true, 
			'is_error' => false, 
		]);

		$json->$type->results = [$qItem->result()];
		$json->status = true;

		return $json;
	}

	/**
	 * Callback for the WP/LR Sync `wpls_update_media` action.
	 *
	 * Lightroom has updated a media item: deletes existing optimisation data, flushes
	 * the filesystem cache, and re-queues the image for optimisation.
	 *
	 * @integration WP / LR Sync (https://meowapps.com/plugin/wplr-sync/)
	 * @param int $imageId WordPress attachment post ID of the updated item.
	 * @return mixed Queue result from `QueueController::addItemToQueue()`.
	 */
	public function onWpLrUpdateMedia($imageId)
	{

		// Get and remove Meta
		$mediaItem = \wpSPIO()->filesystem()->getImage($imageId, 'media');

		$mediaItem->onDelete();

		// Flush and reaquire image to make sure it doesn't stay previous state.
		\wpSPIO()->filesystem()->flushImage($mediaItem);
		$mediaItem = \wpSPIO()->filesystem()->getImage($imageId, 'media', false);

		// Optimize
		$control = new QueueController();
		$json = $control->addItemToQueue($mediaItem);

		return $json;
	}

	/**
	 * Callback for the WP/LR Sync `wpls_sync_media` action.
	 *
	 * Forwards to `onWpLrUpdateMedia()` using the attachment ID from the sync row.
	 *
	 * @integration WP / LR Sync (https://meowapps.com/plugin/wplr-sync/)
	 * @param object $row Sync table row; must contain a `wp_id` property.
	 * @return mixed Queue result forwarded from `onWpLrUpdateMedia()`.
	 */
	public function onWpLrSyncMedia($row)
	{
		$attachment_id = $row->wp_id;
		return $this->onWpLrUpdateMedia($attachment_id);
	}

	/**
	 * Restore an image from its ShortPixel backup.
	 *
	 * Drops the item from the queue if it is currently enqueued, then adds it back with
	 * `action => 'restore'` so the queue processor can run the restore pipeline.
	 *
	 * `$data` keys consumed:
	 * - `id`   int    Image ID.
	 * - `type` string 'media' or 'custom'.
	 *
	 * Returns:
	 * - `$json->$type->results` array  Single-element array with the queue result.
	 * - `$json->status`         bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array with 'id' and 'type'.
	 * @return \stdClass Updated JSON response object.
	 */
	protected function restoreItem($json, $data)
	{
		$id = $data['id'];
		$type = $data['type'];

		$imageModel = $this->getMediaItem($id, $type);

		$this->checkImageAccess($imageModel);

		$queueController = new QueueController();
		$is_in_queue = $queueController->isItemInQueue($imageModel, null);

		if (true === $is_in_queue)
		{
			$queue = $queueController->getQueue($imageModel->get('type')); 
			$queue->dropItem($id);
		}

		$result = $queueController->addItemToQueue($imageModel, ['action' => 'restore']);

		$json->$type->results = [$result];
		$json->status = true;
		return $json;
	}

	/**
	 * Re-optimise an already-optimised image, optionally with a different compression level.
	 *
	 * `$data` keys consumed:
	 * - `id`   int    Image ID.
	 * - `type` string 'media' or 'custom'.
	 *
	 * Additional `$_POST` fields:
	 * - `compressionType` int  Compression level override (0 = plugin default).
	 * - `actionType`      int  Optional smart-crop action constant
	 *                          (`ImageModel::ACTION_SMARTCROP` or `ACTION_SMARTCROPLESS`).
	 *
	 * Returns:
	 * - `$json->$type->results` array  Single-element array with the queue result.
	 * - `$json->$type->qstatus` mixed  Last queue status.
	 * - `$json->status`         bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array with 'id' and 'type'.
	 * @return \stdClass Updated JSON response object.
	 */
	protected function reOptimizeItem($json, $data)
	{
		$id = $data['id'];
		$type = $data['type'];
		$compressionType = isset($_POST['compressionType']) ? intval($_POST['compressionType']) : 0;
		$actionType = isset($_POST['actionType']) ? intval($_POST['actionType']) : null;

		$imageModel = $this->getMediaItem($id, $type);

		$this->checkImageAccess($imageModel);

		$args = ['action' => 'reoptimize', 'compressionType' => $compressionType];

		// Smartcrop is not always passed, only add here when passed otherwise to defaults.
		if ($actionType == ImageModel::ACTION_SMARTCROP || $actionType == ImageModel::ACTION_SMARTCROPLESS) 
		{
			$args['smartcrop'] = $actionType;
		}

		$queueController = new QueueController();
		$result  = $queueController->addItemToQueue($imageModel, $args);

		$json->$type->results = [$result];
		$json->$type->qstatus = $queueController->getLastQueueStatus();

		$json->status = true;

		return $json;
	}

	protected function replaceFileName($data)
	{
		$id = $data['id'];
		$type = $data['type'];	

		$newFileName = isset($_POST['newFileName']) ? sanitize_file_name($_POST['newFileName']) : false; 

		if (false === $newFileName)
		{
		
			$result_json = [
			'error' => __('Something went wrong', 'shortpixel-image-optimiser'), 
			'is_error' => true, 
			];

		 	$result_json['message'] = __('This image could not be loaded', 'shortpixel-image-optimiser'); 
		 	$this->send((object) $result_json);
		}


		$imageModel = $this->getMediaItem($id, $type);
		$this->checkImageAccess($imageModel);
		

		$queueItem = new QueueItem(['imageModel' => $imageModel]);

		$apiController =  $queueItem->getApiController('requestAlt');

		$result = $apiController->ajax_replaceFile($queueItem, $newFileName);

		// Todo Send this QueueItem to the replaceFiles method. 
		$result_json = [
			'is_done' => true, 
			'message' => (true === $result) ? __('Files were replaced', 'shortpixel-image-optimiser') : __('Files were not replaced', 'shortpixel-image-optimiser'),
			'redirect' => 'reload', 
		];

		if (false === $result)
		{
			 $result_json['is_error'] = true; 
		}

		$this->send((object) $result_json);

	}

	/**
	 * Request AI-generated alt text for an image.
	 *
	 * Adds the image to the queue with `action => 'requestAlt'`.  Reads
	 * `$_POST['preview_only']` (presence-only check, default false) to determine
	 * whether the result should be previewed without committing.
	 *
	 * `$data` keys consumed:
	 * - `id`   int    Image ID.
	 * - `type` string 'media' or 'custom'.
	 *
	 * Returns:
	 * - `$json->$type->results`      array  Single-element array with the queue result.
	 * - `$json->$type->qstatus`      mixed  Last queue status.
	 * - `$json->$type->results[0]->apiName` string  Always 'ai' (prevents leaking to
	 *                                                media interface).
	 * - `$json->status`              bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array with 'id' and 'type'.
	 * @return \stdClass Updated JSON response object.
	 */
	protected function requestAlt($json, $data)
	{
		$id = $data['id'];
		$type = $data['type'];

		$preview_only = isset($_POST['preview_only']) ? true : false; 
		$imageModel = $this->getMediaItem($id, $type);

		$queueController = new QueueController();

		$args = [
			'action' => 'requestAlt',
		];
		if (true === $preview_only)
		{
			$args['preview_only'] = true; 
		}
		$result = $queueController->addItemToQueue($imageModel, $args);
		$result->apiName = 'ai'; // prevent response leaking to media interface.
		$json->$type->results = [$result];
		$json->$type->qstatus = $queueController->getLastQueueStatus();
		$json->status = true;

		return $json;
	} 

	/**
	 * Retrieve stored AI alt-text metadata for an image.
	 *
	 * Fetches the alt data via the 'getAltData' API controller and returns it as the
	 * type-keyed object.
	 *
	 * `$data` keys consumed:
	 * - `id`   int    Image ID.
	 * - `type` string 'media' or 'custom'.
	 *
	 * Returns:
	 * - `$json->$type`          object  Populated with the alt metadata fields.
	 * - `$json->$type->results` null    Always null from this method.
	 * - `$json->status`         bool    true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array with 'id' and 'type'.
	 * @return \stdClass Updated JSON response object.
	 */
	protected function getAltData($json, $data)
	{
		 $id = $data['id'];
		 $type = $data['type'];

		 $imageModel = $this->getMediaItem($id, $type); 

		 $this->checkImageAccess($imageModel);

		 $queueItem = new QueueItem(['imageModel' => $imageModel]);

		 $queueItem->getAltDataAction(); 

		 $api = $queueItem->getApiController('getAltData'); 

		 $metadata = $api->getAltData($queueItem);

		 $json->$type = (object) $metadata; 
		 $json->$type->results = null;
		 $json->status = true; 
		 
		 return $json;
	}
	
	/**
	 * Undo or redo the last AI alt-text change for an image.
	 *
	 * Reads `$_POST['action_type']` ('undo' or 'redo', default 'undo').  When
	 * `action_type` is 'redo', delegates directly to `requestAlt()` to re-generate.
	 *
	 * `$data` keys consumed:
	 * - `id`   int    Image ID.
	 * - `type` string 'media' or 'custom'.
	 *
	 * Returns (for 'undo'):
	 * - `$json->$type`  mixed  Alt-data object returned by the API controller.
	 * - `$json->status` bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array with 'id' and 'type'.
	 * @return \stdClass Updated JSON response object.
	 */
	protected function undoAltData($json, $data)
	{
		$id = $data['id'];
		$type = $data['type'];
		// undo or redo
		$action_type = isset($_POST['action_type']) ? sanitize_text_field($_POST['action_type']) : 'undo';

		$imageModel = $this->getMediaItem($id, $type); 
		$this->checkImageAccess($imageModel);


		$queueItem = new QueueItem(['imageModel' => $imageModel]);
		$queueItem->getAltDataAction(); 

		$api = $queueItem->getApiController('getAltData'); 

		$altData = $api->undoAltData($queueItem);

		if ('redo' == $action_type)
		{
			 return $this->requestAlt($json, $data);
		} 

		$json->$type = $altData;
		$json->status = true;
		
		return $json;
	}


	protected function redoAiReplacement($json, $data)
	{
		$id = $data['id'];
		$type = $data['type'];
		
		$imageModel = $this->getMediaItem($id, $type); 
		$this->checkImageAccess($imageModel);
	 

		$queueItem = new QueueItem(['imageModel' => $imageModel]);
		$queueItem->newRedoAiReplacementAction(); 

		$api = $queueItem->getApiController('getAltData'); 

		$api->redoAiReplacement($queueItem);

		$json->status = true;	
		return $json;
	}



	/**
	 * Finalise a bulk run for both media and custom queues.
	 *
	 * If either queue was running a custom operation (restore-all, undo-AI, etc.), sets
	 * `$json->redirect` to the settings/tools page URL.  Calls
	 * `BulkController::finishBulk()` for both 'media' and 'custom'.
	 *
	 * Returns:
	 * - `$json->redirect` string  (Optional) Redirect URL for custom-op runs.
	 * - `$json->status`   int     1.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function finishBulk($json, $data)
	{
		$bulkControl = BulkController::getInstance();

		if (false !== $bulkControl->getAnyCustomOperation()) {
			$json->redirect = add_query_arg(['page' => 'wp-shortpixel-settings', 'part' => 'tools'], admin_url('options-general.php'));
		}

		$bulkControl->finishBulk('media');
		$bulkControl->finishBulk('custom');

		$json->status = 1;

		return $json;
	}


	/**
	 * Create new bulk queues and apply the current selection options.
	 *
	 * Reads optional date-range filters from `$_POST['filter_startdate']` and
	 * `$_POST['filter_enddate']`.  Creates a new bulk for both 'media' (with
	 * `doMedia` and `doAi` args) and 'custom' queues, then calls
	 * `applyBulkSelection()` to apply toggle settings.
	 *
	 * Relevant `$_POST` fields (all read here and in `applyBulkSelection()`):
	 * - `filter_startdate` string  Optional ISO date filter start.
	 * - `filter_enddate`   string  Optional ISO date filter end.
	 * - `mediaActive`      string  Boolean string; whether to process media queue.
	 * - `aiActive`         string  Boolean string; whether to process AI alt-text.
	 *
	 * Returns: see `applyBulkSelection()`.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object from `applyBulkSelection()`.
	 */
	protected function createBulk($json, $data)
	{
		$filters = [];
		$has_filters = false;
		
		if (isset($_POST['filter_startdate'])) 
		{
			 $filters['start_date'] = sanitize_text_field($_POST['filter_startdate']); 
			 $has_filters = true; 	 
		}
		if (isset($_POST['filter_enddate']))
		{
			 $filters['end_date'] = sanitize_text_field($_POST['filter_enddate']); 
			 $has_filters = true; 
		}

		$args = []; 
		if (true === $has_filters)
		{ 
			$args['filters'] = $filters; 
		}

		
		$bulkControl = BulkController::getInstance();
		// This is where the settings start to break and double. This info is also needs inside the process. 
		$doMedia = filter_var(sanitize_text_field($_POST['mediaActive']), FILTER_VALIDATE_BOOLEAN);
		$doAi = filter_var(sanitize_text_field($_POST['aiActive']), FILTER_VALIDATE_BOOLEAN);
		$mediaArgs = array_merge($args, ['doMedia' => $doMedia, 'doAi' => $doAi]);

		$stats = $bulkControl->createNewBulk('media', $mediaArgs);
		$json->media->stats = $stats;

		$stats = $bulkControl->createNewBulk('custom', $args);
		$json->custom->stats = $stats;

		$json = $this->applyBulkSelection($json, $data);
		return $json;
	}

	/**
	 * Persist bulk selection toggles and return updated queue statistics.
	 *
	 * Reads the following `$_POST` fields (all required unless marked optional):
	 * - `mediaActive`       string  Boolean string; enable media queue.
	 * - `customActive`      string  Boolean string; enable custom queue.
	 * - `webpActive`        string  Boolean string; generate WebP variants.
	 * - `avifActive`        string  Boolean string; generate AVIF variants.
	 * - `aiActive`          string  Boolean string; run AI alt-text.
	 * - `backgroundProcess` string  Boolean string; run in background.
	 * - `thumbsActive`      string  (Optional) Boolean string; process thumbnails.
	 * - `aiPreserve`        string  (Optional) Boolean string; preserve existing AI data.
	 *
	 * Side effects: updates `createWebp`, `createAvif`, `doBackgroundProcess`,
	 * `autoAIBulk`, `aiPreserve`, and optionally `processThumbnails` settings.
	 * Calls `BulkController::finishBulk()` for queues that are toggled off.
	 *
	 * Returns:
	 * - `$json->media->stats`  object  Updated media queue statistics.
	 * - `$json->custom->stats` object  Updated custom queue statistics.
	 * - `$json->total`         object  Aggregate totals.
	 * - `$json->status`        bool    true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function applyBulkSelection($json, $data)
	{
		// These values should always be given!
		$doMedia = filter_var(sanitize_text_field($_POST['mediaActive']), FILTER_VALIDATE_BOOLEAN);
		$doCustom = filter_var(sanitize_text_field($_POST['customActive']), FILTER_VALIDATE_BOOLEAN);
		$doWebp = filter_var(sanitize_text_field($_POST['webpActive']), FILTER_VALIDATE_BOOLEAN);
		$doAvif = filter_var(sanitize_text_field($_POST['avifActive']), FILTER_VALIDATE_BOOLEAN);
		$doAi = filter_var(sanitize_text_field($_POST['aiActive']), FILTER_VALIDATE_BOOLEAN);

		$aiPreserve = isset($_POST['aiPreserve']) ? filter_var(sanitize_text_field($_POST['aiPreserve']), FILTER_VALIDATE_BOOLEAN) : null; 
		$backgroundProcess = filter_var(sanitize_text_field($_POST['backgroundProcess']), FILTER_VALIDATE_BOOLEAN);

		// Can be hidden
		if (isset($_POST['thumbsActive'])) {
			$doThumbs = filter_var(sanitize_text_field($_POST['thumbsActive']), FILTER_VALIDATE_BOOLEAN);
			\wpSPIO()->settings()->processThumbnails = $doThumbs;
		}

		\wpSPIO()->settings()->createWebp = $doWebp;
		\wpSPIO()->settings()->createAvif = $doAvif;
		\wpSPIO()->settings()->doBackgroundProcess = $backgroundProcess;
		\wpSPIO()->settings()->autoAIBulk = $doAi;

		if (false === is_null($aiPreserve))
		{
			\wpSPIO()->settings()->aiPreserve = $aiPreserve;
		}

		$bulkControl = BulkController::getInstance();

		if (! $doMedia && ! $doAi) {
			$bulkControl->finishBulk('media');
		}
		if (! $doCustom) {
			$bulkControl->finishBulk('custom');
		}

		$queueController = new QueueController(['is_bulk' => true]);

		$data = $queueController->getStartupData();

		$json->media->stats = $data->media->stats;
		$json->custom->stats = $data->custom->stats;
		$json->total = $data->total;

		$json->status = true;

		return $json;
	}



	/**
	 * Start the bulk run for both media and custom queues.
	 *
	 * Calls `BulkController::startBulk()` with both queue types and sends the
	 * result immediately (does not return to the dispatcher's `send()` call).
	 *
	 * @param \stdClass $json JSON accumulator object (unused; result comes from BulkController).
	 * @param array     $data Dispatch data array (unused).
	 * @return void  Calls send() and exits.
	 */
	protected function startBulk($json, $data)
	{
		$bulkControl = BulkController::getInstance();

		$types = array('media', 'custom');
		$result = $bulkControl->startBulk($types);

		$this->send($result);
	}

	/**
	 * Set up a bulk restore operation for one or both queues.
	 *
	 * Resets all queues first, then creates a new bulk with `customOp => 'bulk-restore'`
	 * for each queue name found in `$_POST['queues']` (comma-separated, 'media' and/or
	 * 'custom').  Returns early without modifying `$json` when no queues are specified.
	 *
	 * Returns:
	 * - `$json->media->stats`  object  (Optional) Stats if 'media' is in queues.
	 * - `$json->custom->stats` object  (Optional) Stats if 'custom' is in queues.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function startRestoreAll($json, $data)
	{
		$bulkControl = BulkController::getInstance();
		QueueController::resetQueues(); // prevent any weirdness

		$queue = (isset($_POST['queues'])) ? sanitize_text_field($_POST['queues']) : false;
		if ($queue === false) // safety first.
			return $json;

		$queues = array_filter(explode(',', $queue), 'trim');

		if (in_array('media', $queues)) {
			$stats = $bulkControl->createNewBulk('media', ['customOp' => 'bulk-restore']);
			$json->media->stats = $stats;
		}

		if (in_array('custom', $queues)) {
			$stats = $bulkControl->createNewBulk('custom', ['customOp' => 'bulk-restore']);
			$json->custom->stats = $stats;
		}

		return $json;
	}

	/**
	 * Set up a bulk undo-AI operation for the media queue.
	 *
	 * Resets all queues, creates a new bulk for 'media' with
	 * `customOp => 'bulk-undoAI'`.
	 *
	 * Returns:
	 * - `$json->media->stats` object  Updated media queue statistics.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function startUndoAI($json, $data)
	{
		$bulkControl = BulkController::getInstance();
		QueueController::resetQueues(); // prevent any weirdness

		$stats = $bulkControl->createNewBulk('media', ['customOp' => 'bulk-undoAI']);
		$json->media->stats = $stats;

		return $json;

	}

	/**
	 * Set up a bulk metadata-migration operation for the media queue.
	 *
	 * Resets all queues, creates a new bulk for 'media' with `customOp => 'migrate'`.
	 *
	 * Returns:
	 * - `$json->media->stats` object  Updated media queue statistics.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function startMigrateAll($json, $data)
	{
		$bulkControl = BulkController::getInstance();
		QueueController::resetQueues(); // prevent any weirdness


		$stats = $bulkControl->createNewBulk('media', ['customOp' => 'migrate']);
		$json->media->stats = $stats;

		return $json;
	}

	protected function startBulkRedoAiReplacement($json, $data)
	{
		$bulkControl = BulkController::getInstance();
		QueueController::resetQueues(); // prevent any weirdness

		$stats = $bulkControl->createNewBulk('media', ['customOp' => 'redoAiReplacement']);
		$json->media->stats = $stats;

		return $json;
	}

	/**
	 * Set up a bulk legacy-file-removal operation for the media queue.
	 *
	 * Resets all queues, creates a new bulk for 'media' with
	 * `customOp => 'removeLegacy'`.
	 *
	 * Returns:
	 * - `$json->media->stats` object  Updated media queue statistics.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function startRemoveLegacy($json, $data)
	{
		$bulkControl = BulkController::getInstance();
		QueueController::resetQueues(); // prevent any weirdness


		$stats = $bulkControl->createNewBulk('media', ['customOp' => 'removeLegacy']);
		$json->media->stats = $stats;

		return $json;
	}

	/**
	 * Migrate a single legacy-format item to the current metadata format.
	 *
	 * Calls `ImageModel::migrate()` on the item.  Sends the result immediately
	 * (does not return to the dispatcher's `send()` call).
	 *
	 * `$data` keys consumed:
	 * - `id`   int    Image ID.
	 * - `type` string 'media' or 'custom'.
	 *
	 * Sends:
	 * - `status`      bool  true.
	 * - `media->id`   int   The image ID.
	 * - `media->type` string 'media'.
	 *
	 * @param \stdClass $json JSON accumulator object (partially populated and sent).
	 * @param array     $data Dispatch data array with 'id' and 'type'.
	 * @return void  Calls send() and exits.
	 */
	protected function redoLegacy($json, $data)
	{
		$id = $data['id'];
		$type = $data['type'];
		$mediaItem = $this->getMediaItem($id, $type);

		$this->checkImageAccess($mediaItem);

		// Changed since updated function should detect what is what.
		$mediaItem->migrate();

		$json->status = true;
		$json->media->id = $id;
		$json->media->type = 'media';
		$this->send($json);
	}

	/**
	 * Persist the user's preferred settings panel mode (simple / advanced).
	 *
	 * Reads `$_POST['new_mode']` (string) and stores it as a user option via
	 * `update_user_option()`.  Returns false without updating when the value is absent.
	 *
	 * @param array $data Dispatch data array (unused).
	 * @return false|void Returns false when new_mode is missing; otherwise void.
	 */
	protected function handleChangeMode($data)
	{
		$user_id = get_current_user_id();
		$new_mode = isset($_POST['new_mode']) ? sanitize_text_field($_POST['new_mode']) : false;

		if (false === $new_mode) {
			return false;
		}

		update_user_option($user_id, 'shortpixel-settings-mode', $new_mode);
	}

	/**
	 * Generate a live AI alt-text preview using temporary settings overrides.
	 *
	 * Reads `$_POST['settingsData']` (JSON-encoded settings overrides, optional) and
	 * `$data['id']` (media attachment ID).  Sends the image through the `requestAlt`
	 * and `retrieveAlt` API stages in a polling loop (up to 30 iterations with 2-second
	 * sleeps).  On completion, stores the result in WordPress transients
	 * (`spio_settings_ai_example_id` and `spio_settings_ai_example`) and sends it.
	 *
	 * Sends and exits on the first of: done, error, or safeguard limit.
	 *
	 * @param array $data Dispatch data array; `$data['id']` is the attachment ID.
	 * @return void  Calls send() and exits.
	 */
	protected function getNewAiImagePreview($data)
	{
		$item_id = $data['id'];
		$settingsData = isset($_POST['settingsData']) ? $_POST['settingsData'] : null; 

		if (! is_null($settingsData))
		{
			 $json = json_decode(stripslashes($settingsData), true);
			 $settings = \wpSPIO()->settings(); 
			 //$settingsData = array_map('sanitize_text_field', $json); 
			 $settingsData = $settings->getSanitizedData($json, false);
		}
		else
		{
			 $settingsData = [];  // null - empty array
		}

		$result_json = [
			'error' => __('Something went wrong', 'shortpixel-image-optimiser'), 
			'is_error' => true, 
		];

		$imageModel = \wpSPIO()->filesystem()->getMediaImage($item_id); 
		

		if (false === $imageModel)
		{
			 $result_json['message'] = __('This image could not be loaded', 'shortpixel-image-optimiser'); 
			 $this->send((object) $result_json);
		}

		$qItem = QueueItems::getImageItem($imageModel);

		$optimizer = $qItem->getApiController('requestAlt');

		$qItem->requestAltAction(array_merge(['preview_only' => true], $settingsData));
		$optimizer->sendToProcessing($qItem);
		$result = $qItem->result(); 
		
		$state = 'requestAlt'; // mimic here the double task of the Ai gen. 
		$is_done = false; 
		$i = 0; 


		while (false === $is_done)
		{

			if (false === property_exists($result, 'is_done') || $result->is_done === false)
			{ 
				$optimizer->sendToProcessing($qItem);
				$result = $qItem->result();
			}
			
			if (property_exists($result, 'is_done') && true === $result->is_done)
			{
				// If is done and is error, bail out. 
				if (true === $result->is_error) 
				{
					$this->send($result->forReturn());
				}
				
				if ('requestAlt' === $state)
				{
					$remote_id = $result->remote_id; 
					
					$result = $optimizer->enqueueItem($qItem, ['preview_only' => true, 'action' => 'retrieveAlt', 'remote_id' => $remote_id]); 
					$state = 'retrieveAlt';
					$result->is_done = false; 
					
				}
				elseif ('retrieveAlt' === $state)
				{
					if (property_exists($result, 'aiData') && false === is_null($result->aiData))
					{
						$aiModel = AiDataModel::getModelByAttachment($qItem->item_id, 'media');

						 $aiData = $optimizer->formatResultData($result->aiData, $qItem);
						 list($items, $aiData) = $optimizer->formatGenerated($aiData, $aiModel->getCurrentData(), $aiModel->getOriginalData(), true);
						 $aiData['item_id'] = $qItem->item_id;
						 $aiData['time_generated'] = time(); 

						 set_transient('spio_settings_ai_example_id', $qItem->item_id, MONTH_IN_SECONDS); 
						 set_transient('spio_settings_ai_example', $aiData, MONTH_IN_SECONDS);
						 
						 $aiData['aiData'] = true; // for the JS check

						 $this->send((object) $aiData);
						 $is_done = true; 
						 break;  // safe guards.

					}
					else
					{
						//Log::addTemp('AiData not set in Ajax');
					}
					
					if ($result->is_done)
					{
					 $this->send($result->forReturn()); 
					 break;
					}
				}
				
			}

			if ('retrieveAlt' === $state)
			{
				sleep(2); // prevent in case of fast connection hammering the API
			}

			if ($i >= 30) // safeguard. 
			{
				Log::addError('Ai Preview bailed after safeguard! ');
				$this->send((object) $result_json);
				break; 
			}
			$i++; 
		}
	}

	/**
	 * Return the current AI alt-text example data for the settings page preview.
	 *
	 * Reads the stored transient (`spio_settings_ai_example_id`) to determine which
	 * image to use.  Falls back to `AiDataModel::getMostRecent()` when no transient is
	 * set.  When no image can be found or loaded, returns a stub with an empty preview.
	 *
	 * Sends:
	 * - `preview_image` string  URL of the best available preview thumbnail.
	 * - `item_id`       int     Attachment ID used for the preview.
	 * - `generated`     array   Generated (AI) alt-text data.
	 * - `original`      array   Current (human) alt-text data.
	 *
	 * @param array $data Dispatch data array (unused; id is read from transient).
	 * @return void  Calls send() and exits.
	 */
	protected function getSettingsAiExample($data)
	{
		$id = get_transient('spio_settings_ai_example_id');

		$attach_id = null; 
		if (false === $id || ! is_numeric($id))
		{
			$item = AiDataModel::getMostRecent();
			if (is_object($item))
			{
				$attach_id = $item->getAttachId(); 
			}
		}
		else
		{
			$item = AiDataModel::getModelByAttachment($id);
			$attach_id = $id; 
		}

		$imageModel = \wpSPIO()->fileSystem()->getMediaImage($attach_id);

        if (is_null($attach_id) || false === $imageModel)
        {
           // make something up
		   $json = [
				'preview_image' => '', 
				'item_id' => -1, 
				'generated' => ['alt' => __('Select an image for example', 'shortpixel-image-optimiser')], 
				'original'	=> [], 
		   ]; 
		   $this->send((object) $json);
        }
        else
        {
		  $transient = get_transient('spio_settings_ai_example'); 
		  if (is_array($transient) && $transient['item_id'] == $id)
		  { 
			 $generated = $transient; 
		  }
		  else
		  {
			$generated = $item->getGeneratedData();
		  }

	 	 // Change 17/04/26 - Current SEO data should always use 'current data' ? 
		 /* if ($item->isSomeThingGenerated())
		  {
          	$original = $item->getOriginalData();
		  }
		  else
		  { */
			 $original = $item->getCurrentData();
		 // }
        }


        $json = [
          'preview_image' => UiHelper::findBestPreview($imageModel)->getURL(), 
		  'item_id' => $attach_id,
          'generated' => $generated, 
          'original' => $original,
        ];

        $this->send((object) $json);
	}

	/**
	 * Persist an attachment as the pinned AI example image and refresh the preview.
	 *
	 * Stores `$data['id']` in the `spio_settings_ai_example_id` transient
	 * (TTL: one month), then delegates to `getSettingsAiExample()`.
	 *
	 * @param array $data Dispatch data array; `$data['id']` is the attachment ID to pin.
	 * @return void  Calls send() (via getSettingsAiExample) and exits.
	 */
	protected function setSettingsAiImage($data)
	{
		 $id = $data['id'];
		 set_transient('spio_settings_ai_example_id', $id, MONTH_IN_SECONDS);

		 return $this->getSettingsAiExample($data);
	}

	

	/**
	 * Return image URLs and dimensions needed to drive the before/after comparer widget.
	 *
	 * Reads `$_POST['id']` and `$_POST['type']`.  Verifies that the current user can
	 * upload files or edit posts; sends an error and exits on failure.
	 *
	 * When the requested item is not itself optimised, falls back to the best optimised
	 * thumbnail via `ImageModel::getSomethingOptimized()`.  For PDF items the 'full'
	 * thumbnail is used instead of the PDF file.
	 *
	 * Sends (via `send()`):
	 * - `origUrl` string  URL of the backup (original) file, or empty string.
	 * - `optUrl`  string  URL of the optimised file.
	 * - `width`   int     Image width in pixels.
	 * - `height`  int     Image height in pixels.
	 *
	 * @param \stdClass $json JSON accumulator object (unused; sends directly).
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return void  Calls send() and exits.
	 */
	protected function getComparerData($json, $data)
	{
		$type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'media';
		$id = isset($_POST['id']) ? intval($_POST['id']) : false;

		if ($id === false || !current_user_can('upload_files') && !current_user_can('edit_posts')) {

			$json->status = false;
			$json->id = $id;
			$json->message = __('Error - item to compare could not be found or no access', 'shortpixel-image-optimiser');
			$this->send($json);
		}

		$ret = array();
		$fs = \wpSPIO()->filesystem();
		$imageObj = $fs->getImage($id, $type);
		$mainImage = clone $imageObj;

		$this->checkImageAccess($imageObj);


		if (false === $imageObj->isOptimized())
		{
			$imageObj = $imageObj->getSomethingOptimized();
		}

		// With PDF, the thumbnail called 'full' is the image, the main is the PDF file
		if ($imageObj->getExtension() == 'pdf') {
			$thumbImg = $imageObj->getThumbnail('full');
			if ($thumbImg !== false) {
				$imageObj = $thumbImg;
			}
		}

		$backupModel = $imageObj->getBackupModel(); 	
		$mainBackupFile = $backupModel->getMainBackupFile();

		$backupFile = $backupModel->getBackupFile($imageObj);
		if (is_object($backupFile))
			$backup_url = $fs->pathToUrl($backupFile);
		elseif (is_object($mainBackupFile))
		{
			$backup_url = $fs->pathToUrl($mainBackupFile);
		}
		else
		{
			$backup_url = '';
		}

		$ret['origUrl'] = $backup_url; // $backupUrl . $urlBkPath . $meta->getName();

		$ret['optUrl'] = $imageObj->getURL();
		$ret['width'] = $imageObj->getMeta('originalWidth');
		$ret['height'] = $imageObj->getMeta('originalHeight');

		if (is_null($ret['width']) || $ret['width'] == false) {

			if (! $imageObj->is_virtual()) {
				$ret['width'] = $imageObj->get('width');
				$ret['height'] = $imageObj->get('height');
			} else {
				$size = getimagesize($backupFile->getFullPath());
				if (is_array($size)) {
					$ret['width'] = $size[0];
					$ret['height'] = $size[1];
				}
			}
		}

		$this->send((object) $ret);
	}

	/**
	 * Force a content refresh on a specific custom media folder.
	 *
	 * Reads `$_POST['id']` (int, folder database ID).  Calls
	 * `DirectoryOtherMediaModel::refreshFolder(true)` and returns a status message
	 * describing how many files were added.
	 *
	 * Returns:
	 * - `$json->folder->message`   string  Human-readable refresh result.
	 * - `$json->folder->fileCount` int     Current file count in the folder.
	 * - `$json->folder->action`    string  Always 'refresh'.
	 * - `$json->folder->updated`   string  Formatted last-updated timestamp.
	 * - `$json->folder->id`        int     The folder ID.
	 * - `$json->folder->is_error`  bool    (Optional) Set on error conditions.
	 * - `$json->status`            bool    true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function refreshFolder($json, $data)
	{
		$otherMediaController = OtherMediaController::getInstance();

		$folder_id = isset($_POST['id']) ? intval($_POST['id']) : false;
		$json->folder->message = '';


		if (false === $folder_id) {
			$json->folder->is_error = true;
			$json->folder->message = __('An error has occured: no folder id', 'shortpixel-image-optimiser');
		}

		$folderObj = $otherMediaController->getFolderByID($folder_id);

		if (false === $folderObj) {
			$json->folder->is_error = true;
			$json->folder->message = __('An error has occured: no folder object', 'shortpixel-image-optimiser');
		}

		$result = $folderObj->refreshFolder(true);

		if (false === $result) {
			$json->folder->message = $folderObj->get('last_message');
		} else { // result is stats
			$stats = $result;
			if ($stats['new'] > 0) {
				$message = sprintf(__('%s new files found ( %s waiting %s optimized)', 'shortpixel-image-optimiser'), $stats['new'], $stats['waiting'], $stats['optimized']);
			} else {
				$message = sprintf(__('No new files found ( %s waiting %s optimized)', 'shortpixel-image-optimiser'), $stats['waiting'], $stats['optimized']);
			}

			$json->folder->message = $message;
		}


		$json->status = true;
		$json->folder->fileCount = $folderObj->get('fileCount');
		$json->folder->action = 'refresh';
		$json->folder->updated = UiHelper::formatTS($folderObj->get('updated'));
		$json->folder->id = $folder_id;

		return $json;
	}

	/**
	 * Remove a custom media folder from the plugin's tracking database.
	 *
	 * Reads `$_POST['id']` (int, folder database ID).  Returns early with an error
	 * (without returning `$json`) when the folder cannot be found — note that `$json`
	 * is not returned in the error path, which means the caller's `send()` will still
	 * fire with the partially-populated object.
	 *
	 * Returns:
	 * - `$json->folder->message` string  Confirmation or error text.
	 * - `$json->folder->is_done` bool    true on success.
	 * - `$json->folder->action`  string  Always 'remove'.
	 * - `$json->folder->id`      int     The folder ID.
	 * - `$json->status`          bool    true on success.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass|void Updated JSON object, or void on early error return.
	 */
	protected function removeCustomFolder($json, $data)
	{
		$folder_id = isset($_POST['id']) ? intval($_POST['id']) : false;

		$otherMedia = OtherMediaController::getInstance();
		$dirObj = $otherMedia->getFolderByID($folder_id);

		if ($dirObj === false) {
			$json->folder->is_error = true;
			$json->folder->message = __('An error has occured: no folder object', 'shortpixel-image-optimiser');
			return;
		}

		$dirObj->delete();

		$json->status = true;
		$json->folder->message = __('Folder has been removed', 'shortpixel-image-optimiser');
		$json->folder->is_done = true;
		$json->folder->action = 'remove';
		$json->folder->id = $folder_id;
		

		return $json;
	}

	/**
	 * Register a new custom media folder and return its rendered list-row HTML.
	 *
	 * Reads `$_POST['relpath']` (string, relative path under the WP file base).
	 * Delegates to `OtherMediaController::addDirectory()`.  On success, renders the
	 * single-item view via `OtherMediaFolderViewController::singleItemView()`.
	 *
	 * Also appends any newly queued admin notices to the response.
	 *
	 * Returns:
	 * - `$json->folder->result->id`       int    The new folder's database ID.
	 * - `$json->folder->result->itemView` string Rendered HTML for the folder row.
	 * - `$json->folder->is_error`         bool   (Optional) true on failure.
	 * - `$json->folder->message`          string (Optional) Error message.
	 * - `$json->notices`                  array  (Optional) New admin notice objects.
	 * - `$json->display_notices`          array  (Optional) Display-ready notice HTML.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function addCustomFolder($json, $data)
	{
		$relpath = isset($_POST['relpath']) ? sanitize_text_field($_POST['relpath']) : null;

		$fs = \wpSPIO()->filesystem();

		$customFolderBase = $fs->getWPFileBase();
		$basePath = $customFolderBase->getPath();

		$path = trailingslashit($basePath) . $relpath;

		$otherMedia = OtherMediaController::getInstance();

		// Result is a folder object
		$result = $otherMedia->addDirectory($path);

		if (false === $result) {
			$json->folder->is_error = true;
			$json->folder->message = __('Failed to add Folder', 'shortpixel-image-optimiser');
		} else {
			$control = new OtherMediaFolderViewController();
			$itemView = $control->singleItemView($result);

			$json->folder->result = new \stdClass;
			$json->folder->result->id = $result->get('id');
			$json->folder->result->itemView = $itemView;
		}

		$noticeController = Notices::getInstance();
		$json->notices = $noticeController->getNewNotices();

		if (count($json->notices) > 0) {
			$json->display_notices = [];
			foreach ($json->notices as $notice) {
				$json->display_notices[] = $notice->getForDisplay(['class' => 'is_ajax', 'is_removable' => false]);
			}
		}
		$noticeController->update(); // dismiss one-time ponies
		return $json;
	}

	/**
	 * Return a list of subdirectories under the given relative path for the folder browser.
	 *
	 * Reads `$_POST['relPath']` (string, URL-encoded relative path, default '').
	 * Delegates to `OtherMediaController::browseFolder()`.
	 *
	 * Returns:
	 * - `$json->folder->folders`  array  Folder descriptor arrays (or empty on error).
	 * - `$json->folder->relpath`  string The requested relative path.
	 * - `$json->folder->is_error` bool   (Optional) true on error.
	 * - `$json->folder->message`  string (Optional) Error message.
	 * - `$json->status`           bool   true.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function browseFolders($json, $data)
	{
		$relpath = isset($_POST['relPath']) ? sanitize_text_field($_POST['relPath']) : '';

		$otherMediaController = OtherMediaController::getInstance();

		$folders = $otherMediaController->browseFolder($relpath);

		if (isset($folders['is_error']) && true == $folders['is_error']) {
			$json->folder->is_error = true;
			$json->folder->message = $folders['message'];
			$folders = array();
		}

		$json->folder->folders = $folders;
		$json->folder->relpath = $relpath;
		$json->status = true;

		return $json;
	}

	/**
	 * Reset all custom-folder scan timestamps so every folder is rescanned next tick.
	 *
	 * Delegates to `OtherMediaController::resetCheckedTimestamps()`.
	 *
	 * @param \stdClass $json JSON accumulator object (returned unchanged).
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass The unchanged JSON accumulator.
	 */
	protected function resetScanFolderChecked($json, $data)
	{
		$otherMediaController = OtherMediaController::getInstance();

		$otherMediaController->resetCheckedTimestamps();
		return $json;
	}

	/**
	 * Refresh the next custom folder that is due for a content scan.
	 *
	 * Reads `$_POST['force']` (string or null) and passes it to
	 * `OtherMediaController::doNextRefreshableFolder()`.  When no folder needs
	 * refreshing, sets `is_done` and a completion message.
	 *
	 * Returns:
	 * - `$json->folder->is_done`  bool   (Optional) true when all folders are scanned.
	 * - `$json->folder->result`   mixed  Folder scan result object, or completion stdClass.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused; values read from $_POST).
	 * @return \stdClass Updated JSON response object.
	 */
	protected function scanNextFolder($json, $data)
	{
		$otherMediaController = OtherMediaController::getInstance();
		$force = isset($_POST['force']) ? sanitize_text_field($_POST['force']) : null;

		$args = array();
		$args['force'] = $force;

		$result = $otherMediaController->doNextRefreshableFolder($args);

		if ($result === false) {
			$json->folder->is_done = true;
			$json->folder->result = new \stdClass;
			$json->folder->result->message = __('All Folders have been scanned!', 'shortpixel-image-optimiser');
		} else {

			$json->folder->result = $result;
		}

		return $json;
	}

	/*
	public function ajax_getBackupFolderSize()
	{
		$this->checkNonce('ajax_request');
		$this->checkActionAccess($action, 'is_editor');

		$dirObj = \wpSPIO()->filesystem()->getDirectory(SHORTPIXEL_BACKUP_FOLDER);

		$size = $dirObj->getFolderSize();
		echo UiHelper::formatBytes($size);
		exit();
	}
	*/

	/**
	 * AJAX handler: force a remote quota refresh and report the current state.
	 *
	 * Action: `wp_ajax_shortpixel_checkquota`.
	 *
	 * Verifies the nonce (`ajax_request`) and `is_author` capability.  Forces a live
	 * remote quota check, then returns the result.  If quota is exceeded, also queues
	 * an admin warning notice.
	 *
	 * Sends (via `wp_send_json()`):
	 * - `status`   string  'has-quota' or 'no-quota'.
	 * - `redirect` string  Sanitised HTTP referer URL.
	 *
	 * @return void  Always exits via wp_send_json().
	 */
	public function ajax_checkquota()
	{

		$this->checkNonce('ajax_request');
		$action = 'check_quota';
		$this->checkActionAccess($action, 'is_author');

		$quotaController = QuotaController::getInstance();
		$quotaController->forceCheckRemoteQuota();

		$quota = $quotaController->getQuota();

		$settings = \wpSPIO()->settings();

		$sendback = wp_get_referer();
		// sanitize the referring webpage location
		$sendback = preg_replace('|[^a-z0-9-~+_.?#=&;,/:]|i', '', $sendback);

		$result = array('status' => 'no-quota', 'redirect' => $sendback);
		if (! $settings->quotaExceeded) {
			$result['status'] = 'has-quota';
		} else {
			Notices::addWarning(__('You have no available image credits. If you just bought a package, please note that sometimes it takes a few minutes for the payment processor to send us the payment confirmation.', 'shortpixel-image-optimiser'));
		}

		wp_send_json($result);
	}



	/**
	 * Load and parse a bulk-run log file for display in the UI.
	 *
	 * `$data` keys consumed:
	 * - `type`    string  'media' or 'custom' — keys the response namespace.
	 * - `logFile` string  Base filename (without '.log') passed from the dispatch layer.
	 *             This is originally read from `$_POST['loadFile']` in `ajaxRequest()`.
	 *
	 * Parses the semicolon-delimited log file into row arrays with date, filename, id,
	 * error, link, kblink, and (for custom) path fields.  Prepends a header row.
	 *
	 * Returns:
	 * - `$json->$type->logType`  string  'media' or 'custom'.
	 * - `$json->$type->title`    string  Formatted "Bulk ran on …" heading.
	 * - `$json->$type->results`  array   Parsed rows (first row = headers).
	 * - `$json->$type->is_error` bool    (Optional) true when the file cannot be found.
	 * - `$json->$type->result`   string  (Optional) Error message text.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array with 'logFile' and 'type'.
	 * @return \stdClass Updated JSON response object.
	 */
	protected function loadLogFile($json, $data)
	{
		$logFile = $data['logFile'] . '.log';
		$type = $data['type'];
		$fs = \wpSPIO()->filesystem();

		if (is_null($logFile)) {
			$json->$type->is_error = true;
			$json->$type->result = __('Could not load log file', 'shortpixel-image-optimiser');
			return $json;
		}

		$bulkController = BulkController::getInstance();
		$log = $bulkController->getLog($logFile);
		$logData = $bulkController->getLogData($logFile);

		$logType = $logData['type']; // custom or media.

		$json->$type->logType = $logType;

		if (false === $log) {
			$json->$type->is_error = true;
			$json->$type->result = __('Log file does not exist', 'shortpixel-image-optimiser');
			return $json;
		}

		$date = (isset($logData['date'])) ? UiHelper::formatTS($logData['date']) : false;
		$content = trim($log->getContents());
		$lines = array_filter(explode(';', $content));

		$headers = [
			__('Time', 'shortpixel-image-optimiser'),
			__('Filename', 'shortpixel-image-optimiser'),
			__('ID', 'shortpixel-image-optimiser'),
			__('Error', 'shortpixel-image-optimiser'),
		];

		if ('custom' == $logType) {
			array_splice($headers, 3, 0, __('Info', 'shortpixel-image-optimiser'));
		}

		foreach ($lines as $index => $line) {
			$cells = array_filter(explode('|', $line));

			$date = $cells[0];
			$filename = $cells[1];
			$id = isset($cells[2]) ? $cells[2] : false;
			$error = isset($cells[3]) ? $cells[3] : false;

			$line = ['date' => $date, 'filename' => $filename, 'id' => $id, 'error' => $error];

			if ($id !== false && $logType !== 'custom') {
				// replaces the image id with a link to image.
				$line['link'] = esc_url(admin_url('post.php?post=' . trim($id) . '&action=edit'));
			} elseif ($logType === 'custom') {
				$base = esc_url(admin_url('upload.php?page=wp-short-pixel-custom'));
				$line['link'] = add_query_arg('s', sanitize_text_field($filename), $base);
			}

			if ($error !== false) {
				$line['kblink'] = UiHelper::getKBSearchLink($error);
			}

			if ('custom' == $logType && $id !== false) {
				$imageObj = $fs->getImage($id, 'custom');
				if (is_object($imageObj)) {
					$dir = $imageObj->getFileDir();
					if (is_object($dir)) {
						$path = $dir->getRelativePath();
						$line['path'] = $path;
					}
				}
			}

			$lines[$index] = $line;
		}
		$lines = array_values(array_filter($lines));
		array_unshift($lines, $headers);
		$json->$type->title = sprintf(__('Bulk ran on %s', 'shortpixel-image-optimiser'), $date);
		$json->$type->results = $lines;
		return $json;
	}

	/**
	 * Verify the WordPress nonce for the current AJAX request.
	 *
	 * Reads `$_POST['nonce']` and validates it against `$action`.  On failure, sends
	 * a JSON error response with `error = NONCE_FAILED` and exits.  This method does
	 * not return false — a failed nonce always terminates the request.
	 *
	 * @param string $action The nonce action string (e.g. 'processing', 'ajax_request').
	 * @return void  Returns normally on success; exits on failure.
	 */
	protected function checkNonce($action)
	{
		if (! wp_verify_nonce($_POST['nonce'], $action)) {

			$id = isset($_POST['id']) ? intval($_POST['id']) : false;
			$action = isset($_POST['screen_action']) ? sanitize_text_field($_POST['screen_action']) : false;

			$json = new \stdClass;
			$json->message = __('Nonce is missing or wrong - Try to refresh the page', 'shortpixel-image-optimiser');
			$json->item_id = $id;
			$json->action = $action;
			$json->status = false;
			$json->error = self::NONCE_FAILED;
			$this->send($json);
			exit();
		}
	}

	/**
	 * Verify that the current user has the required capability for an action.
	 *
	 * Delegates to `AccessModel::userIsAllowed()` with the provided `$access` level
	 * (e.g. 'is_author', 'is_editor', 'is_admin_user', 'is_super_admin' — the latter
	 * used by the site-wide tools `toolsRemoveAll` / `toolsRemoveBackup`). On failure,
	 * sends a JSON error with `error = NO_ACCESS` and exits.
	 *
	 * @param string $action The action name (used only for the error message).
	 * @param string $access The capability level string as understood by AccessModel.
	 * @return true  Returns true on success; exits on failure.
	 */
	protected function checkActionAccess($action, $access)
	{
		$accessModel = AccessModel::getInstance();

		$bool = $accessModel->userIsAllowed($access);

		if ($bool === false) {
			$json = new \stdClass;
			$json->message = __('This user is not allowed to perform this action', 'shortpixel-image-optimiser');
			$json->action = $action;
			$json->status = false;
			$json->error = self::NO_ACCESS;
			$this->send($json);
			exit();
		}

		return true;
	}

	/**
	 * Verify that the current user may edit the given image.
	 *
	 * Accepts either a valid image model object or a non-object (false/null) for cases
	 * where the image could not be loaded.  Calls `AccessModel::imageIsEditable()`.
	 * On failure (image not found or user not allowed), sends a JSON error with
	 * `error = NO_ACCESS` and exits.
	 *
	 * @param \ShortPixel\Model\Image\ImageModel|false $mediaItem The image model to check, or false.
	 * @return true  Returns true on success; exits on failure.
	 */
	protected function checkImageAccess($mediaItem)
	{

		// defaults
		$message = __('This user is not allowed to edit this image', 'shortpixel-image-optimiser');

		$accessModel = AccessModel::getInstance();
		if (is_object($mediaItem)) {
			$bool = $accessModel->imageIsEditable($mediaItem);
			$id = $mediaItem->get('id');

		} else {
			$bool = false;
			$id = false;
			if (! is_object($mediaItem))
			{
				$message = __('Image does not exist or could not be loaded', 'shortpixel-image-optimiser');
			}
		}

		if ($bool === false) {
			$json = new \stdClass;
			$json->message = $message; 
			$json->status = false;
			$json->id = $id;
			$json->error = self::NO_ACCESS;
			$this->send($json);
			exit();
		}

		return true;
	}

	/**
	 * Send a JSON response to the browser and terminate the request.
	 *
	 * Casts non-stdClass objects to stdClass to avoid serialisation issues.  Appends
	 * `callback` from `$_POST['callback']` (if present) and the current processor key
	 * to the response before calling `wp_send_json()`.
	 *
	 * @param \stdClass|array|object $json The response payload to serialise.
	 * @return void  Always exits via wp_send_json().
	 */
	protected function send($json)
	{
		// Cast before sending anything to a simple stdclass, to prevent issues with adding json and processorkey to output 
		if ( (is_object($json) && false === $json instanceof \stdClass)  || is_array($json))
		{
			$json = (object) $json; 
		}

		$callback = isset($_POST['callback']) ? sanitize_text_field($_POST['callback']) : false;
		if ($callback)
			$json->callback = $callback; // which type of request we just fullfilled ( response processing )

		$pKey = $this->getProcessorKey();
		if ($pKey !== false)
			$json->processorKey = $pKey;

		wp_send_json($json);
		exit();
	}


	/**
	 * Hard-uninstall the plugin: remove all data and deactivate.
	 *
	 * Verifies a secondary nonce from `$_POST['tools-nonce']` (action 'remove-all')
	 * in addition to the outer `ajax_request` nonce.  On success, calls
	 * `InstallHelper::hardUninstall()` and redirects to the plugins page.
	 *
	 * Returns:
	 * - `$json->settings->results`  string  Confirmation or (logged) error message.
	 * - `$json->settings->redirect` string  URL to redirect the browser to.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	private function removeAllData($json, $data)
	{
		if (1 === wp_verify_nonce($_POST['tools-nonce'], 'remove-all')) {
			InstallHelper::hardUninstall();
			$json->settings->results = __('All Data has been removed. The plugin has been deactivated', 'shortpixel-image-optimiser');
		} else {
			Log::addError('RemoveAll detected with wrong nonce');
		}

		$json->settings->redirect = admin_url('plugins.php');

		return $json;
	}

	/**
	 * Delete all ShortPixel backup files from the backup folder.
	 *
	 * Verifies a secondary nonce from `$_POST['tools-nonce']` (action 'empty-backup').
	 * Moves log files to a temp directory, recursively deletes the backup folder, then
	 * moves log files back.
	 *
	 * Returns:
	 * - `$json->settings->results` string  Confirmation or error text.
	 *
	 * @param \stdClass $json JSON accumulator object.
	 * @param array     $data Dispatch data array (unused).
	 * @return \stdClass Updated JSON response object.
	 */
	private function removeBackup($json, $data)
	{
		if (wp_verify_nonce($_POST['tools-nonce'], 'empty-backup')) {			

			$fs = \wpSPIO()->filesystem(); 
			
			$fs->moveLogFiles(); 

			$dir = \wpSPIO()->filesystem()->getDirectory(SHORTPIXEL_BACKUP_FOLDER);
			$dir->recursiveDelete(); 

			$fs->moveLogFiles(['to_temp' => false]);

			$json->settings->results = __('The backups have been removed. You can close the window', 'shortpixel-image-optimiser');
		} else {
			$json->settings->results = __('Error: Invalid Nonce in empty backups', 'shortpixel-image-optimiser');
		}

		return $json;
	}
}
