version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password_2019
      MYSQL_DATABASE: wordpress

#TODO Wordpress doesn't yet work properly. Cannot connect to database MySQL Connection Error: (1130) Host '172.18.0.3' is not allowed to connect to this MySQL server
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: Password_2019
volumes:
  db_data: {}