
<?php 
$icon_url = plugins_url( '/res/images/icon/', SHORTPIXEL_PLUGIN_FILE ); 
$robo_icon = $icon_url . '/robo.svg'; 
$ai_icon = $icon_url . '/ai.svg'; 

$item_id = $this->data['item_id']; 
$has_data = $this->data['has_data'];

if (false === $has_data): 
?>
        <label></label>
        <a class='button button-secondary' href="javascript:window.ShortPixelProcessor.screen.RequestAlt(<?php echo $item_id ?>)">
			<img class="shortpixel-ai-icon ai" src="<?php echo $ai_icon ?>">	
			<span><?php _e('AI Captioning - by ShortPixel', 'shortpixel-image-optimiser') ?></span>
			<img class="shortpixel-ai-icon robo" src="<?php echo $robo_icon ?>">
		</a>
        <div class="shortpixel-alt-messagebox" id="shortpixel-ai-messagebox-<?php echo $item_id ?>">&nbsp;</div>
        
<?php else : 
	
	$lb = '%0D%0A';
	$mailtolink = "mailto:support@shortpixel.com?Subject=Wrong caption generated by ShortPixel AI&Body=ImageURL:  " . $this->data['image_url'] . "$lb $lb Caption:  " . $this->data['result_alt']; 
?>

	<p><?php _e('Caption generated by ShortPixel AI', 'shortpixel-image-optimiser'); ?></p>
	<a class='button button-secondary' href="javascript:window.ShortPixelProcessor.screen.UndoAlt(<?php echo $item_id ?>)"><?php _e('Undo', 'shortpixel-image-optimiser'); ?></a>
	<a class='button button-secondary' href="<?php echo $mailtolink ?>"><?php _e('Report wrong caption', 'shortpixel-image-optimiser'); ?></a>

<?php endif; ?>
        