<?php

use ShortPixel\Controller\ApiKeyController;
use ShortPixel\Controller\QuotaController;

$icon_url = plugins_url( '/res/images/icon/', SHORTPIXEL_PLUGIN_FILE ); 
$robo_icon = $icon_url . '/shortpixel.svg'; 
$ai_icon = $icon_url . '/ai.svg'; 

$item_id = $this->data['item_id']; 
$has_data = $this->data['has_data'];
$isSupported = $this->data['isSupported'];

$quotaControl = QuotaController::getInstance();
$keyControl = ApiKeyController::getInstance();

if (true === apply_filters('shortpixel/settings/no_ai', false)):

	?>
	<p class='hidden' id='shortpixel-noai'></p>
<?php

elseif (false === $isSupported):

	?>
		<p><?php _e('Currently, ShortPixel AI cannot generate ALT tags for GIF files.', 'shortpixel-image-optimiser'); ?></p>
	<?php 

elseif (false === $has_data): 

	if (false === $keyControl->keyIsVerified() && false === $has_data):
	
  		_e('Invalid API Key. <a href="options-general.php?page=wp-shortpixel-settings">Check your Settings</a>','shortpixel-image-optimiser');

	elseif (false === $quotaControl->hasQuota() && false === $has_data):
	?>
	<p><?php _e('ShortPixel quota exhausted, the ALT tag cannot be generated.', 'shortpixel-image-optimiser'); ?></p>

	<?php else: ?>

        <a class='button button-secondary' title="Generate the alternative text with ShortPixel AI (Beta)" href="javascript:window.ShortPixelProcessor.screen.RequestAlt(<?php echo $item_id ?>)">
			<img class="shortpixel-ai-icon ai" src="<?php echo $ai_icon ?>">	
			<span><?php _e('Image ALT by ShortPixel', 'shortpixel-image-optimiser') ?></span>
			<img class="shortpixel-ai-icon shortpixel" src="<?php echo $robo_icon ?>">
		</a>
        <div class="shortpixel-alt-messagebox" id="shortpixel-ai-messagebox-<?php echo $item_id ?>">&nbsp;</div>
	<?php endif; ?>   
<?php else : 
	
	$lb = '%0D%0A';
	$mailtolink = "mailto:support@shortpixel.com?Subject=Wrong caption generated by ShortPixel AI&Body=ImageURL:  " . $this->data['image_url'] . "$lb $lb Caption:  " . $this->data['result_alt']; 
?>

	<p><?php _e('Image ALT generated by ShortPixel AI', 'shortpixel-image-optimiser'); ?><img class="shortpixel-ai-caption shortpixel-ai-icon shortpixel" src="<?php echo $robo_icon ?>"></p>
	<a class='button button-secondary' title="Restores the previous ALT tag, if available." href="javascript:window.ShortPixelProcessor.screen.UndoAlt(<?php echo $item_id ?>)"><?php _e('Undo', 'shortpixel-image-optimiser'); ?></a>
	<a class='button button-secondary' title="Report to us, via e-mail, an incorrect ALT tag for this image." href="<?php echo $mailtolink ?>"><?php _e('Report', 'shortpixel-image-optimiser'); ?></a>
	<a class='button button-secondary' title="Send us feedback about this feature, suggest other features, or vote on existing feature requests." target="_blank" href="https://ideas.shortpixel.com/"><?php _e('Feedback', 'shortpixel-image-optimiser'); ?></a>

<?php endif; ?>
