<?php

if ( ! defined( 'ABSPATH' ) ) {
 exit; // Exit if accessed directly.
}

use ShortPixel\Controller\ApiKeyController;
use ShortPixel\Controller\QuotaController;
use ShortPixel\Model\AiDataModel;

$icon_url = plugins_url( '/res/images/icon/', SHORTPIXEL_PLUGIN_FILE ); 
$robo_icon = $icon_url . '/shortpixel.svg'; 
$ai_icon = $icon_url . '/ai.svg'; 

$item_id = $this->data['item_id']; 
$has_data = $this->data['has_data'];
//$isSupported = $this->data['isSupported'];
$isDifferent = $this->data['isDifferent'];
$dataItems = implode(', ',$this->data['dataItems']);

$is_processable = $this->data['is_processable']; 
$is_renameable = $this->data['is_renameable'];
$processable_reason = $this->data['processable_reason'];
$processable_status = $this->data['processable_status'];
$filename = $this->data['filename'];

$quotaControl = QuotaController::getInstance();
$keyControl = ApiKeyController::getInstance();

$files_replace_success = isset($_POST['replace_done']) ? true : false;  


if (true === apply_filters('shortpixel/settings/no_ai', false)):

	?>
	<p class='hidden' id='shortpixel-noai'></p>
<?php
endif;

if (false === $is_processable && $processable_status !== AiDataModel::P_ALREADYDONE):

	if (true === in_array($processable_status, [AiDataModel::P_NOJOB])) // Silent fail if all done
	{

	}
	else
	{
		printf('<p>%s</p>', esc_html($processable_reason));
	}
	

elseif (false === $has_data): 

	if (false === $keyControl->keyIsVerified() && false === $has_data):
	
  		_e('Invalid API Key. <a href="options-general.php?page=wp-shortpixel-settings">Check your Settings</a>','shortpixel-image-optimiser');

	elseif (false === $quotaControl->hasQuota() && false === $has_data):
	?>
	<p><?php _e('ShortPixel quota exhausted, the image SEO data cannot be generated.', 'shortpixel-image-optimiser'); ?></p>

	<?php else: ?>

        <a class='button button-secondary' title="<?php esc_attr_e('Generate image SEO data with ShortPixel AI', 'shortpixel-image-optimiser'); ?>" href="javascript:window.ShortPixelProcessor.screen.RequestAlt(<?php echo esc_attr($item_id); ?>)">
			<img class="shortpixel-ai-icon ai" src="<?php echo esc_url($ai_icon); ?>">	
			<span><?php printf(__('AI Image SEO by ShortPixel %s', 'shortpixel-image-optimiser'), esc_html($dataItems)) ?></span>
			<img class="shortpixel-ai-icon shortpixel" src="<?php echo esc_url($robo_icon); ?>">
		</a>
        <div class="shortpixel-alt-messagebox" id="shortpixel-ai-messagebox-<?php echo $item_id ?>">&nbsp;</div>
	<?php endif; ?>   
<?php else : 
	
	$lb = '%0D%0A';
	$mailtolink = "mailto:support@shortpixel.com?Subject=Wrong AI SEO data generated by ShortPixel AI&Body=ImageURL:  " . rawurlencode($this->data['image_url']) . "$lb $lb Caption:  " . rawurlencode($this->data['result_alt']);
?>

	<p><img class="shortpixel-ai-caption shortpixel-ai-icon shortpixel" src="<?php echo esc_url($robo_icon); ?>"> <?php printf(__('The following image SEO data was generated by ShortPixel AI: %s', 'shortpixel-image-optimiser'), '<strong>' . esc_html($dataItems) . '</strong>') ?></p>
	
	<a class='button button-secondary' title="<?php _e('Restores the previous image SEO data, if available.', 'shortpixel-image-optimiser'); ?>" href="javascript:window.ShortPixelProcessor.screen.UndoAlt(<?php echo $item_id ?>, 'undo')"><?php _e('Undo', 'shortpixel-image-optimiser'); ?></a>

	<?php if (true === $isDifferent): ?>

	<a class='button button-secondary' title="<?php _e('Redo', 'shortpixel-image-optimiser'); ?>" href="javascript:window.ShortPixelProcessor.screen.UndoAlt(<?php echo $item_id ?>, 'redo')"><?php _e('Redo', 'shortpixel-image-optimiser'); ?></a>
	<?php endif; ?>

	<a class='button button-secondary' title="<?php _e('Report incorrect image SEO data for this image to us by e-mail.', 'shortpixel-image-optimiser') ?>" href="<?php echo esc_attr($mailtolink); ?>"><?php _e('Report', 'shortpixel-image-optimiser'); ?></a>

	<a class='button button-secondary' title="<?php _e('Send us feedback about this feature, suggest other features, or vote on existing feature requests.', 'shortpixel-image-optimiser'); ?>" target="_blank" href="https://ideas.shortpixel.com/"><?php _e('Feedback', 'shortpixel-image-optimiser'); ?></a>

	<?php if (true === $isDifferent)
	{
		 printf(__('%s The plugin has detected that some fields were changed after the image SEO data was generated. You can use the Redo button to generate it again. %s', 'shortpixel-image-optimiser'), '<p>', '</p>');
	} ?>

<?php endif; ?>

<?php if (true === $is_renameable) : ?> 
<div class="shortpixel-ai-replace-file hidden">
	<?php _e('Filename:', 'shortpixel-image-optimiser'); ?>
	<input type="text" name="filename_replace" value="<?php echo esc_attr($filename); ?>" 
	title="<?php _e('Warning - If this image is already indexed by search engines, please note that no automatic redirects are being added!', 'shortpixel-image-optimiser'); ?>">
	
	<span class="copy-to-clipboard-container">
	<button type="button" class='button button-secondary' name="filename_replace_submit" value="1"><?php _e('Change Filename', 'shortpixel-image-optimiser') ?></button>
	</span>

	<?php if (true === $files_replace_success)
	{
		printf(__('%s Files successfully replaced! %s', 'shortpixel-image-optimiser'), '<p>', '</p>');
	}
	?>
</div>
<?php endif; ?> 